package com.roughindustries.commonwealthcocktails.mybatis.model;

public class Categories {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column categories.idcategory
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private Integer idcategory;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column categories.category_name
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private String categoryName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column categories.idcategory
	 * @return  the value of categories.idcategory
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public Integer getIdcategory() {
		return idcategory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column categories.idcategory
	 * @param idcategory  the value for categories.idcategory
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setIdcategory(Integer idcategory) {
		this.idcategory = idcategory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column categories.category_name
	 * @return  the value of categories.category_name
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public String getCategoryName() {
		return categoryName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column categories.category_name
	 * @param categoryName  the value for categories.category_name
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}
}