package com.roughindustries.commonwealthcocktails.mybatis.model;

public class Cocktail {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cocktail.idcocktail
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private Integer idcocktail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cocktail.cocktail_name
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private String cocktailName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cocktail.cocktail_method
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private String cocktailMethod;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cocktail.cocktail_thumbnail
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private String cocktailThumbnail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cocktail.cocktail_fullpage
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private String cocktailFullpage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cocktail.cocktail_video
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private String cocktailVideo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cocktail.cocktail_style
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private String cocktailStyle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cocktail.cocktail_aka
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private String cocktailAka;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cocktail.cocktail_alternate_name
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private String cocktailAlternateName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cocktail.cocktail_display_name
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private String cocktailDisplayName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cocktail.cocktail_echo_name
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private String cocktailEchoName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cocktail.cocktail_origin
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private String cocktailOrigin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cocktail.cocktail_comment
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private String cocktailComment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cocktail.cocktail_rating
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private String cocktailRating;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cocktail.idcocktail
	 * @return  the value of cocktail.idcocktail
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public Integer getIdcocktail() {
		return idcocktail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cocktail.idcocktail
	 * @param idcocktail  the value for cocktail.idcocktail
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setIdcocktail(Integer idcocktail) {
		this.idcocktail = idcocktail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cocktail.cocktail_name
	 * @return  the value of cocktail.cocktail_name
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public String getCocktailName() {
		return cocktailName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cocktail.cocktail_name
	 * @param cocktailName  the value for cocktail.cocktail_name
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setCocktailName(String cocktailName) {
		this.cocktailName = cocktailName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cocktail.cocktail_method
	 * @return  the value of cocktail.cocktail_method
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public String getCocktailMethod() {
		return cocktailMethod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cocktail.cocktail_method
	 * @param cocktailMethod  the value for cocktail.cocktail_method
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setCocktailMethod(String cocktailMethod) {
		this.cocktailMethod = cocktailMethod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cocktail.cocktail_thumbnail
	 * @return  the value of cocktail.cocktail_thumbnail
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public String getCocktailThumbnail() {
		return cocktailThumbnail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cocktail.cocktail_thumbnail
	 * @param cocktailThumbnail  the value for cocktail.cocktail_thumbnail
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setCocktailThumbnail(String cocktailThumbnail) {
		this.cocktailThumbnail = cocktailThumbnail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cocktail.cocktail_fullpage
	 * @return  the value of cocktail.cocktail_fullpage
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public String getCocktailFullpage() {
		return cocktailFullpage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cocktail.cocktail_fullpage
	 * @param cocktailFullpage  the value for cocktail.cocktail_fullpage
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setCocktailFullpage(String cocktailFullpage) {
		this.cocktailFullpage = cocktailFullpage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cocktail.cocktail_video
	 * @return  the value of cocktail.cocktail_video
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public String getCocktailVideo() {
		return cocktailVideo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cocktail.cocktail_video
	 * @param cocktailVideo  the value for cocktail.cocktail_video
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setCocktailVideo(String cocktailVideo) {
		this.cocktailVideo = cocktailVideo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cocktail.cocktail_style
	 * @return  the value of cocktail.cocktail_style
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public String getCocktailStyle() {
		return cocktailStyle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cocktail.cocktail_style
	 * @param cocktailStyle  the value for cocktail.cocktail_style
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setCocktailStyle(String cocktailStyle) {
		this.cocktailStyle = cocktailStyle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cocktail.cocktail_aka
	 * @return  the value of cocktail.cocktail_aka
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public String getCocktailAka() {
		return cocktailAka;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cocktail.cocktail_aka
	 * @param cocktailAka  the value for cocktail.cocktail_aka
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setCocktailAka(String cocktailAka) {
		this.cocktailAka = cocktailAka;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cocktail.cocktail_alternate_name
	 * @return  the value of cocktail.cocktail_alternate_name
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public String getCocktailAlternateName() {
		return cocktailAlternateName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cocktail.cocktail_alternate_name
	 * @param cocktailAlternateName  the value for cocktail.cocktail_alternate_name
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setCocktailAlternateName(String cocktailAlternateName) {
		this.cocktailAlternateName = cocktailAlternateName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cocktail.cocktail_display_name
	 * @return  the value of cocktail.cocktail_display_name
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public String getCocktailDisplayName() {
		return cocktailDisplayName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cocktail.cocktail_display_name
	 * @param cocktailDisplayName  the value for cocktail.cocktail_display_name
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setCocktailDisplayName(String cocktailDisplayName) {
		this.cocktailDisplayName = cocktailDisplayName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cocktail.cocktail_echo_name
	 * @return  the value of cocktail.cocktail_echo_name
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public String getCocktailEchoName() {
		return cocktailEchoName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cocktail.cocktail_echo_name
	 * @param cocktailEchoName  the value for cocktail.cocktail_echo_name
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setCocktailEchoName(String cocktailEchoName) {
		this.cocktailEchoName = cocktailEchoName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cocktail.cocktail_origin
	 * @return  the value of cocktail.cocktail_origin
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public String getCocktailOrigin() {
		return cocktailOrigin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cocktail.cocktail_origin
	 * @param cocktailOrigin  the value for cocktail.cocktail_origin
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setCocktailOrigin(String cocktailOrigin) {
		this.cocktailOrigin = cocktailOrigin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cocktail.cocktail_comment
	 * @return  the value of cocktail.cocktail_comment
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public String getCocktailComment() {
		return cocktailComment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cocktail.cocktail_comment
	 * @param cocktailComment  the value for cocktail.cocktail_comment
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setCocktailComment(String cocktailComment) {
		this.cocktailComment = cocktailComment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cocktail.cocktail_rating
	 * @return  the value of cocktail.cocktail_rating
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public String getCocktailRating() {
		return cocktailRating;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cocktail.cocktail_rating
	 * @param cocktailRating  the value for cocktail.cocktail_rating
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setCocktailRating(String cocktailRating) {
		this.cocktailRating = cocktailRating;
	}
}