package com.roughindustries.commonwealthcocktails.mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class CocktailExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cocktail
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cocktail
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cocktail
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cocktail
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public CocktailExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cocktail
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cocktail
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cocktail
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cocktail
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cocktail
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cocktail
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cocktail
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cocktail
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cocktail
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cocktail
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table cocktail
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdcocktailIsNull() {
			addCriterion("idcocktail is null");
			return (Criteria) this;
		}

		public Criteria andIdcocktailIsNotNull() {
			addCriterion("idcocktail is not null");
			return (Criteria) this;
		}

		public Criteria andIdcocktailEqualTo(Integer value) {
			addCriterion("idcocktail =", value, "idcocktail");
			return (Criteria) this;
		}

		public Criteria andIdcocktailNotEqualTo(Integer value) {
			addCriterion("idcocktail <>", value, "idcocktail");
			return (Criteria) this;
		}

		public Criteria andIdcocktailGreaterThan(Integer value) {
			addCriterion("idcocktail >", value, "idcocktail");
			return (Criteria) this;
		}

		public Criteria andIdcocktailGreaterThanOrEqualTo(Integer value) {
			addCriterion("idcocktail >=", value, "idcocktail");
			return (Criteria) this;
		}

		public Criteria andIdcocktailLessThan(Integer value) {
			addCriterion("idcocktail <", value, "idcocktail");
			return (Criteria) this;
		}

		public Criteria andIdcocktailLessThanOrEqualTo(Integer value) {
			addCriterion("idcocktail <=", value, "idcocktail");
			return (Criteria) this;
		}

		public Criteria andIdcocktailIn(List<Integer> values) {
			addCriterion("idcocktail in", values, "idcocktail");
			return (Criteria) this;
		}

		public Criteria andIdcocktailNotIn(List<Integer> values) {
			addCriterion("idcocktail not in", values, "idcocktail");
			return (Criteria) this;
		}

		public Criteria andIdcocktailBetween(Integer value1, Integer value2) {
			addCriterion("idcocktail between", value1, value2, "idcocktail");
			return (Criteria) this;
		}

		public Criteria andIdcocktailNotBetween(Integer value1, Integer value2) {
			addCriterion("idcocktail not between", value1, value2, "idcocktail");
			return (Criteria) this;
		}

		public Criteria andCocktailNameIsNull() {
			addCriterion("cocktail_name is null");
			return (Criteria) this;
		}

		public Criteria andCocktailNameIsNotNull() {
			addCriterion("cocktail_name is not null");
			return (Criteria) this;
		}

		public Criteria andCocktailNameEqualTo(String value) {
			addCriterion("cocktail_name =", value, "cocktailName");
			return (Criteria) this;
		}

		public Criteria andCocktailNameNotEqualTo(String value) {
			addCriterion("cocktail_name <>", value, "cocktailName");
			return (Criteria) this;
		}

		public Criteria andCocktailNameGreaterThan(String value) {
			addCriterion("cocktail_name >", value, "cocktailName");
			return (Criteria) this;
		}

		public Criteria andCocktailNameGreaterThanOrEqualTo(String value) {
			addCriterion("cocktail_name >=", value, "cocktailName");
			return (Criteria) this;
		}

		public Criteria andCocktailNameLessThan(String value) {
			addCriterion("cocktail_name <", value, "cocktailName");
			return (Criteria) this;
		}

		public Criteria andCocktailNameLessThanOrEqualTo(String value) {
			addCriterion("cocktail_name <=", value, "cocktailName");
			return (Criteria) this;
		}

		public Criteria andCocktailNameLike(String value) {
			addCriterion("cocktail_name like", value, "cocktailName");
			return (Criteria) this;
		}

		public Criteria andCocktailNameNotLike(String value) {
			addCriterion("cocktail_name not like", value, "cocktailName");
			return (Criteria) this;
		}

		public Criteria andCocktailNameIn(List<String> values) {
			addCriterion("cocktail_name in", values, "cocktailName");
			return (Criteria) this;
		}

		public Criteria andCocktailNameNotIn(List<String> values) {
			addCriterion("cocktail_name not in", values, "cocktailName");
			return (Criteria) this;
		}

		public Criteria andCocktailNameBetween(String value1, String value2) {
			addCriterion("cocktail_name between", value1, value2, "cocktailName");
			return (Criteria) this;
		}

		public Criteria andCocktailNameNotBetween(String value1, String value2) {
			addCriterion("cocktail_name not between", value1, value2, "cocktailName");
			return (Criteria) this;
		}

		public Criteria andCocktailMethodIsNull() {
			addCriterion("cocktail_method is null");
			return (Criteria) this;
		}

		public Criteria andCocktailMethodIsNotNull() {
			addCriterion("cocktail_method is not null");
			return (Criteria) this;
		}

		public Criteria andCocktailMethodEqualTo(String value) {
			addCriterion("cocktail_method =", value, "cocktailMethod");
			return (Criteria) this;
		}

		public Criteria andCocktailMethodNotEqualTo(String value) {
			addCriterion("cocktail_method <>", value, "cocktailMethod");
			return (Criteria) this;
		}

		public Criteria andCocktailMethodGreaterThan(String value) {
			addCriterion("cocktail_method >", value, "cocktailMethod");
			return (Criteria) this;
		}

		public Criteria andCocktailMethodGreaterThanOrEqualTo(String value) {
			addCriterion("cocktail_method >=", value, "cocktailMethod");
			return (Criteria) this;
		}

		public Criteria andCocktailMethodLessThan(String value) {
			addCriterion("cocktail_method <", value, "cocktailMethod");
			return (Criteria) this;
		}

		public Criteria andCocktailMethodLessThanOrEqualTo(String value) {
			addCriterion("cocktail_method <=", value, "cocktailMethod");
			return (Criteria) this;
		}

		public Criteria andCocktailMethodLike(String value) {
			addCriterion("cocktail_method like", value, "cocktailMethod");
			return (Criteria) this;
		}

		public Criteria andCocktailMethodNotLike(String value) {
			addCriterion("cocktail_method not like", value, "cocktailMethod");
			return (Criteria) this;
		}

		public Criteria andCocktailMethodIn(List<String> values) {
			addCriterion("cocktail_method in", values, "cocktailMethod");
			return (Criteria) this;
		}

		public Criteria andCocktailMethodNotIn(List<String> values) {
			addCriterion("cocktail_method not in", values, "cocktailMethod");
			return (Criteria) this;
		}

		public Criteria andCocktailMethodBetween(String value1, String value2) {
			addCriterion("cocktail_method between", value1, value2, "cocktailMethod");
			return (Criteria) this;
		}

		public Criteria andCocktailMethodNotBetween(String value1, String value2) {
			addCriterion("cocktail_method not between", value1, value2, "cocktailMethod");
			return (Criteria) this;
		}

		public Criteria andCocktailThumbnailIsNull() {
			addCriterion("cocktail_thumbnail is null");
			return (Criteria) this;
		}

		public Criteria andCocktailThumbnailIsNotNull() {
			addCriterion("cocktail_thumbnail is not null");
			return (Criteria) this;
		}

		public Criteria andCocktailThumbnailEqualTo(String value) {
			addCriterion("cocktail_thumbnail =", value, "cocktailThumbnail");
			return (Criteria) this;
		}

		public Criteria andCocktailThumbnailNotEqualTo(String value) {
			addCriterion("cocktail_thumbnail <>", value, "cocktailThumbnail");
			return (Criteria) this;
		}

		public Criteria andCocktailThumbnailGreaterThan(String value) {
			addCriterion("cocktail_thumbnail >", value, "cocktailThumbnail");
			return (Criteria) this;
		}

		public Criteria andCocktailThumbnailGreaterThanOrEqualTo(String value) {
			addCriterion("cocktail_thumbnail >=", value, "cocktailThumbnail");
			return (Criteria) this;
		}

		public Criteria andCocktailThumbnailLessThan(String value) {
			addCriterion("cocktail_thumbnail <", value, "cocktailThumbnail");
			return (Criteria) this;
		}

		public Criteria andCocktailThumbnailLessThanOrEqualTo(String value) {
			addCriterion("cocktail_thumbnail <=", value, "cocktailThumbnail");
			return (Criteria) this;
		}

		public Criteria andCocktailThumbnailLike(String value) {
			addCriterion("cocktail_thumbnail like", value, "cocktailThumbnail");
			return (Criteria) this;
		}

		public Criteria andCocktailThumbnailNotLike(String value) {
			addCriterion("cocktail_thumbnail not like", value, "cocktailThumbnail");
			return (Criteria) this;
		}

		public Criteria andCocktailThumbnailIn(List<String> values) {
			addCriterion("cocktail_thumbnail in", values, "cocktailThumbnail");
			return (Criteria) this;
		}

		public Criteria andCocktailThumbnailNotIn(List<String> values) {
			addCriterion("cocktail_thumbnail not in", values, "cocktailThumbnail");
			return (Criteria) this;
		}

		public Criteria andCocktailThumbnailBetween(String value1, String value2) {
			addCriterion("cocktail_thumbnail between", value1, value2, "cocktailThumbnail");
			return (Criteria) this;
		}

		public Criteria andCocktailThumbnailNotBetween(String value1, String value2) {
			addCriterion("cocktail_thumbnail not between", value1, value2, "cocktailThumbnail");
			return (Criteria) this;
		}

		public Criteria andCocktailFullpageIsNull() {
			addCriterion("cocktail_fullpage is null");
			return (Criteria) this;
		}

		public Criteria andCocktailFullpageIsNotNull() {
			addCriterion("cocktail_fullpage is not null");
			return (Criteria) this;
		}

		public Criteria andCocktailFullpageEqualTo(String value) {
			addCriterion("cocktail_fullpage =", value, "cocktailFullpage");
			return (Criteria) this;
		}

		public Criteria andCocktailFullpageNotEqualTo(String value) {
			addCriterion("cocktail_fullpage <>", value, "cocktailFullpage");
			return (Criteria) this;
		}

		public Criteria andCocktailFullpageGreaterThan(String value) {
			addCriterion("cocktail_fullpage >", value, "cocktailFullpage");
			return (Criteria) this;
		}

		public Criteria andCocktailFullpageGreaterThanOrEqualTo(String value) {
			addCriterion("cocktail_fullpage >=", value, "cocktailFullpage");
			return (Criteria) this;
		}

		public Criteria andCocktailFullpageLessThan(String value) {
			addCriterion("cocktail_fullpage <", value, "cocktailFullpage");
			return (Criteria) this;
		}

		public Criteria andCocktailFullpageLessThanOrEqualTo(String value) {
			addCriterion("cocktail_fullpage <=", value, "cocktailFullpage");
			return (Criteria) this;
		}

		public Criteria andCocktailFullpageLike(String value) {
			addCriterion("cocktail_fullpage like", value, "cocktailFullpage");
			return (Criteria) this;
		}

		public Criteria andCocktailFullpageNotLike(String value) {
			addCriterion("cocktail_fullpage not like", value, "cocktailFullpage");
			return (Criteria) this;
		}

		public Criteria andCocktailFullpageIn(List<String> values) {
			addCriterion("cocktail_fullpage in", values, "cocktailFullpage");
			return (Criteria) this;
		}

		public Criteria andCocktailFullpageNotIn(List<String> values) {
			addCriterion("cocktail_fullpage not in", values, "cocktailFullpage");
			return (Criteria) this;
		}

		public Criteria andCocktailFullpageBetween(String value1, String value2) {
			addCriterion("cocktail_fullpage between", value1, value2, "cocktailFullpage");
			return (Criteria) this;
		}

		public Criteria andCocktailFullpageNotBetween(String value1, String value2) {
			addCriterion("cocktail_fullpage not between", value1, value2, "cocktailFullpage");
			return (Criteria) this;
		}

		public Criteria andCocktailVideoIsNull() {
			addCriterion("cocktail_video is null");
			return (Criteria) this;
		}

		public Criteria andCocktailVideoIsNotNull() {
			addCriterion("cocktail_video is not null");
			return (Criteria) this;
		}

		public Criteria andCocktailVideoEqualTo(String value) {
			addCriterion("cocktail_video =", value, "cocktailVideo");
			return (Criteria) this;
		}

		public Criteria andCocktailVideoNotEqualTo(String value) {
			addCriterion("cocktail_video <>", value, "cocktailVideo");
			return (Criteria) this;
		}

		public Criteria andCocktailVideoGreaterThan(String value) {
			addCriterion("cocktail_video >", value, "cocktailVideo");
			return (Criteria) this;
		}

		public Criteria andCocktailVideoGreaterThanOrEqualTo(String value) {
			addCriterion("cocktail_video >=", value, "cocktailVideo");
			return (Criteria) this;
		}

		public Criteria andCocktailVideoLessThan(String value) {
			addCriterion("cocktail_video <", value, "cocktailVideo");
			return (Criteria) this;
		}

		public Criteria andCocktailVideoLessThanOrEqualTo(String value) {
			addCriterion("cocktail_video <=", value, "cocktailVideo");
			return (Criteria) this;
		}

		public Criteria andCocktailVideoLike(String value) {
			addCriterion("cocktail_video like", value, "cocktailVideo");
			return (Criteria) this;
		}

		public Criteria andCocktailVideoNotLike(String value) {
			addCriterion("cocktail_video not like", value, "cocktailVideo");
			return (Criteria) this;
		}

		public Criteria andCocktailVideoIn(List<String> values) {
			addCriterion("cocktail_video in", values, "cocktailVideo");
			return (Criteria) this;
		}

		public Criteria andCocktailVideoNotIn(List<String> values) {
			addCriterion("cocktail_video not in", values, "cocktailVideo");
			return (Criteria) this;
		}

		public Criteria andCocktailVideoBetween(String value1, String value2) {
			addCriterion("cocktail_video between", value1, value2, "cocktailVideo");
			return (Criteria) this;
		}

		public Criteria andCocktailVideoNotBetween(String value1, String value2) {
			addCriterion("cocktail_video not between", value1, value2, "cocktailVideo");
			return (Criteria) this;
		}

		public Criteria andCocktailStyleIsNull() {
			addCriterion("cocktail_style is null");
			return (Criteria) this;
		}

		public Criteria andCocktailStyleIsNotNull() {
			addCriterion("cocktail_style is not null");
			return (Criteria) this;
		}

		public Criteria andCocktailStyleEqualTo(String value) {
			addCriterion("cocktail_style =", value, "cocktailStyle");
			return (Criteria) this;
		}

		public Criteria andCocktailStyleNotEqualTo(String value) {
			addCriterion("cocktail_style <>", value, "cocktailStyle");
			return (Criteria) this;
		}

		public Criteria andCocktailStyleGreaterThan(String value) {
			addCriterion("cocktail_style >", value, "cocktailStyle");
			return (Criteria) this;
		}

		public Criteria andCocktailStyleGreaterThanOrEqualTo(String value) {
			addCriterion("cocktail_style >=", value, "cocktailStyle");
			return (Criteria) this;
		}

		public Criteria andCocktailStyleLessThan(String value) {
			addCriterion("cocktail_style <", value, "cocktailStyle");
			return (Criteria) this;
		}

		public Criteria andCocktailStyleLessThanOrEqualTo(String value) {
			addCriterion("cocktail_style <=", value, "cocktailStyle");
			return (Criteria) this;
		}

		public Criteria andCocktailStyleLike(String value) {
			addCriterion("cocktail_style like", value, "cocktailStyle");
			return (Criteria) this;
		}

		public Criteria andCocktailStyleNotLike(String value) {
			addCriterion("cocktail_style not like", value, "cocktailStyle");
			return (Criteria) this;
		}

		public Criteria andCocktailStyleIn(List<String> values) {
			addCriterion("cocktail_style in", values, "cocktailStyle");
			return (Criteria) this;
		}

		public Criteria andCocktailStyleNotIn(List<String> values) {
			addCriterion("cocktail_style not in", values, "cocktailStyle");
			return (Criteria) this;
		}

		public Criteria andCocktailStyleBetween(String value1, String value2) {
			addCriterion("cocktail_style between", value1, value2, "cocktailStyle");
			return (Criteria) this;
		}

		public Criteria andCocktailStyleNotBetween(String value1, String value2) {
			addCriterion("cocktail_style not between", value1, value2, "cocktailStyle");
			return (Criteria) this;
		}

		public Criteria andCocktailAkaIsNull() {
			addCriterion("cocktail_aka is null");
			return (Criteria) this;
		}

		public Criteria andCocktailAkaIsNotNull() {
			addCriterion("cocktail_aka is not null");
			return (Criteria) this;
		}

		public Criteria andCocktailAkaEqualTo(String value) {
			addCriterion("cocktail_aka =", value, "cocktailAka");
			return (Criteria) this;
		}

		public Criteria andCocktailAkaNotEqualTo(String value) {
			addCriterion("cocktail_aka <>", value, "cocktailAka");
			return (Criteria) this;
		}

		public Criteria andCocktailAkaGreaterThan(String value) {
			addCriterion("cocktail_aka >", value, "cocktailAka");
			return (Criteria) this;
		}

		public Criteria andCocktailAkaGreaterThanOrEqualTo(String value) {
			addCriterion("cocktail_aka >=", value, "cocktailAka");
			return (Criteria) this;
		}

		public Criteria andCocktailAkaLessThan(String value) {
			addCriterion("cocktail_aka <", value, "cocktailAka");
			return (Criteria) this;
		}

		public Criteria andCocktailAkaLessThanOrEqualTo(String value) {
			addCriterion("cocktail_aka <=", value, "cocktailAka");
			return (Criteria) this;
		}

		public Criteria andCocktailAkaLike(String value) {
			addCriterion("cocktail_aka like", value, "cocktailAka");
			return (Criteria) this;
		}

		public Criteria andCocktailAkaNotLike(String value) {
			addCriterion("cocktail_aka not like", value, "cocktailAka");
			return (Criteria) this;
		}

		public Criteria andCocktailAkaIn(List<String> values) {
			addCriterion("cocktail_aka in", values, "cocktailAka");
			return (Criteria) this;
		}

		public Criteria andCocktailAkaNotIn(List<String> values) {
			addCriterion("cocktail_aka not in", values, "cocktailAka");
			return (Criteria) this;
		}

		public Criteria andCocktailAkaBetween(String value1, String value2) {
			addCriterion("cocktail_aka between", value1, value2, "cocktailAka");
			return (Criteria) this;
		}

		public Criteria andCocktailAkaNotBetween(String value1, String value2) {
			addCriterion("cocktail_aka not between", value1, value2, "cocktailAka");
			return (Criteria) this;
		}

		public Criteria andCocktailAlternateNameIsNull() {
			addCriterion("cocktail_alternate_name is null");
			return (Criteria) this;
		}

		public Criteria andCocktailAlternateNameIsNotNull() {
			addCriterion("cocktail_alternate_name is not null");
			return (Criteria) this;
		}

		public Criteria andCocktailAlternateNameEqualTo(String value) {
			addCriterion("cocktail_alternate_name =", value, "cocktailAlternateName");
			return (Criteria) this;
		}

		public Criteria andCocktailAlternateNameNotEqualTo(String value) {
			addCriterion("cocktail_alternate_name <>", value, "cocktailAlternateName");
			return (Criteria) this;
		}

		public Criteria andCocktailAlternateNameGreaterThan(String value) {
			addCriterion("cocktail_alternate_name >", value, "cocktailAlternateName");
			return (Criteria) this;
		}

		public Criteria andCocktailAlternateNameGreaterThanOrEqualTo(String value) {
			addCriterion("cocktail_alternate_name >=", value, "cocktailAlternateName");
			return (Criteria) this;
		}

		public Criteria andCocktailAlternateNameLessThan(String value) {
			addCriterion("cocktail_alternate_name <", value, "cocktailAlternateName");
			return (Criteria) this;
		}

		public Criteria andCocktailAlternateNameLessThanOrEqualTo(String value) {
			addCriterion("cocktail_alternate_name <=", value, "cocktailAlternateName");
			return (Criteria) this;
		}

		public Criteria andCocktailAlternateNameLike(String value) {
			addCriterion("cocktail_alternate_name like", value, "cocktailAlternateName");
			return (Criteria) this;
		}

		public Criteria andCocktailAlternateNameNotLike(String value) {
			addCriterion("cocktail_alternate_name not like", value, "cocktailAlternateName");
			return (Criteria) this;
		}

		public Criteria andCocktailAlternateNameIn(List<String> values) {
			addCriterion("cocktail_alternate_name in", values, "cocktailAlternateName");
			return (Criteria) this;
		}

		public Criteria andCocktailAlternateNameNotIn(List<String> values) {
			addCriterion("cocktail_alternate_name not in", values, "cocktailAlternateName");
			return (Criteria) this;
		}

		public Criteria andCocktailAlternateNameBetween(String value1, String value2) {
			addCriterion("cocktail_alternate_name between", value1, value2, "cocktailAlternateName");
			return (Criteria) this;
		}

		public Criteria andCocktailAlternateNameNotBetween(String value1, String value2) {
			addCriterion("cocktail_alternate_name not between", value1, value2, "cocktailAlternateName");
			return (Criteria) this;
		}

		public Criteria andCocktailDisplayNameIsNull() {
			addCriterion("cocktail_display_name is null");
			return (Criteria) this;
		}

		public Criteria andCocktailDisplayNameIsNotNull() {
			addCriterion("cocktail_display_name is not null");
			return (Criteria) this;
		}

		public Criteria andCocktailDisplayNameEqualTo(String value) {
			addCriterion("cocktail_display_name =", value, "cocktailDisplayName");
			return (Criteria) this;
		}

		public Criteria andCocktailDisplayNameNotEqualTo(String value) {
			addCriterion("cocktail_display_name <>", value, "cocktailDisplayName");
			return (Criteria) this;
		}

		public Criteria andCocktailDisplayNameGreaterThan(String value) {
			addCriterion("cocktail_display_name >", value, "cocktailDisplayName");
			return (Criteria) this;
		}

		public Criteria andCocktailDisplayNameGreaterThanOrEqualTo(String value) {
			addCriterion("cocktail_display_name >=", value, "cocktailDisplayName");
			return (Criteria) this;
		}

		public Criteria andCocktailDisplayNameLessThan(String value) {
			addCriterion("cocktail_display_name <", value, "cocktailDisplayName");
			return (Criteria) this;
		}

		public Criteria andCocktailDisplayNameLessThanOrEqualTo(String value) {
			addCriterion("cocktail_display_name <=", value, "cocktailDisplayName");
			return (Criteria) this;
		}

		public Criteria andCocktailDisplayNameLike(String value) {
			addCriterion("cocktail_display_name like", value, "cocktailDisplayName");
			return (Criteria) this;
		}

		public Criteria andCocktailDisplayNameNotLike(String value) {
			addCriterion("cocktail_display_name not like", value, "cocktailDisplayName");
			return (Criteria) this;
		}

		public Criteria andCocktailDisplayNameIn(List<String> values) {
			addCriterion("cocktail_display_name in", values, "cocktailDisplayName");
			return (Criteria) this;
		}

		public Criteria andCocktailDisplayNameNotIn(List<String> values) {
			addCriterion("cocktail_display_name not in", values, "cocktailDisplayName");
			return (Criteria) this;
		}

		public Criteria andCocktailDisplayNameBetween(String value1, String value2) {
			addCriterion("cocktail_display_name between", value1, value2, "cocktailDisplayName");
			return (Criteria) this;
		}

		public Criteria andCocktailDisplayNameNotBetween(String value1, String value2) {
			addCriterion("cocktail_display_name not between", value1, value2, "cocktailDisplayName");
			return (Criteria) this;
		}

		public Criteria andCocktailEchoNameIsNull() {
			addCriterion("cocktail_echo_name is null");
			return (Criteria) this;
		}

		public Criteria andCocktailEchoNameIsNotNull() {
			addCriterion("cocktail_echo_name is not null");
			return (Criteria) this;
		}

		public Criteria andCocktailEchoNameEqualTo(String value) {
			addCriterion("cocktail_echo_name =", value, "cocktailEchoName");
			return (Criteria) this;
		}

		public Criteria andCocktailEchoNameNotEqualTo(String value) {
			addCriterion("cocktail_echo_name <>", value, "cocktailEchoName");
			return (Criteria) this;
		}

		public Criteria andCocktailEchoNameGreaterThan(String value) {
			addCriterion("cocktail_echo_name >", value, "cocktailEchoName");
			return (Criteria) this;
		}

		public Criteria andCocktailEchoNameGreaterThanOrEqualTo(String value) {
			addCriterion("cocktail_echo_name >=", value, "cocktailEchoName");
			return (Criteria) this;
		}

		public Criteria andCocktailEchoNameLessThan(String value) {
			addCriterion("cocktail_echo_name <", value, "cocktailEchoName");
			return (Criteria) this;
		}

		public Criteria andCocktailEchoNameLessThanOrEqualTo(String value) {
			addCriterion("cocktail_echo_name <=", value, "cocktailEchoName");
			return (Criteria) this;
		}

		public Criteria andCocktailEchoNameLike(String value) {
			addCriterion("cocktail_echo_name like", value, "cocktailEchoName");
			return (Criteria) this;
		}

		public Criteria andCocktailEchoNameNotLike(String value) {
			addCriterion("cocktail_echo_name not like", value, "cocktailEchoName");
			return (Criteria) this;
		}

		public Criteria andCocktailEchoNameIn(List<String> values) {
			addCriterion("cocktail_echo_name in", values, "cocktailEchoName");
			return (Criteria) this;
		}

		public Criteria andCocktailEchoNameNotIn(List<String> values) {
			addCriterion("cocktail_echo_name not in", values, "cocktailEchoName");
			return (Criteria) this;
		}

		public Criteria andCocktailEchoNameBetween(String value1, String value2) {
			addCriterion("cocktail_echo_name between", value1, value2, "cocktailEchoName");
			return (Criteria) this;
		}

		public Criteria andCocktailEchoNameNotBetween(String value1, String value2) {
			addCriterion("cocktail_echo_name not between", value1, value2, "cocktailEchoName");
			return (Criteria) this;
		}

		public Criteria andCocktailOriginIsNull() {
			addCriterion("cocktail_origin is null");
			return (Criteria) this;
		}

		public Criteria andCocktailOriginIsNotNull() {
			addCriterion("cocktail_origin is not null");
			return (Criteria) this;
		}

		public Criteria andCocktailOriginEqualTo(String value) {
			addCriterion("cocktail_origin =", value, "cocktailOrigin");
			return (Criteria) this;
		}

		public Criteria andCocktailOriginNotEqualTo(String value) {
			addCriterion("cocktail_origin <>", value, "cocktailOrigin");
			return (Criteria) this;
		}

		public Criteria andCocktailOriginGreaterThan(String value) {
			addCriterion("cocktail_origin >", value, "cocktailOrigin");
			return (Criteria) this;
		}

		public Criteria andCocktailOriginGreaterThanOrEqualTo(String value) {
			addCriterion("cocktail_origin >=", value, "cocktailOrigin");
			return (Criteria) this;
		}

		public Criteria andCocktailOriginLessThan(String value) {
			addCriterion("cocktail_origin <", value, "cocktailOrigin");
			return (Criteria) this;
		}

		public Criteria andCocktailOriginLessThanOrEqualTo(String value) {
			addCriterion("cocktail_origin <=", value, "cocktailOrigin");
			return (Criteria) this;
		}

		public Criteria andCocktailOriginLike(String value) {
			addCriterion("cocktail_origin like", value, "cocktailOrigin");
			return (Criteria) this;
		}

		public Criteria andCocktailOriginNotLike(String value) {
			addCriterion("cocktail_origin not like", value, "cocktailOrigin");
			return (Criteria) this;
		}

		public Criteria andCocktailOriginIn(List<String> values) {
			addCriterion("cocktail_origin in", values, "cocktailOrigin");
			return (Criteria) this;
		}

		public Criteria andCocktailOriginNotIn(List<String> values) {
			addCriterion("cocktail_origin not in", values, "cocktailOrigin");
			return (Criteria) this;
		}

		public Criteria andCocktailOriginBetween(String value1, String value2) {
			addCriterion("cocktail_origin between", value1, value2, "cocktailOrigin");
			return (Criteria) this;
		}

		public Criteria andCocktailOriginNotBetween(String value1, String value2) {
			addCriterion("cocktail_origin not between", value1, value2, "cocktailOrigin");
			return (Criteria) this;
		}

		public Criteria andCocktailCommentIsNull() {
			addCriterion("cocktail_comment is null");
			return (Criteria) this;
		}

		public Criteria andCocktailCommentIsNotNull() {
			addCriterion("cocktail_comment is not null");
			return (Criteria) this;
		}

		public Criteria andCocktailCommentEqualTo(String value) {
			addCriterion("cocktail_comment =", value, "cocktailComment");
			return (Criteria) this;
		}

		public Criteria andCocktailCommentNotEqualTo(String value) {
			addCriterion("cocktail_comment <>", value, "cocktailComment");
			return (Criteria) this;
		}

		public Criteria andCocktailCommentGreaterThan(String value) {
			addCriterion("cocktail_comment >", value, "cocktailComment");
			return (Criteria) this;
		}

		public Criteria andCocktailCommentGreaterThanOrEqualTo(String value) {
			addCriterion("cocktail_comment >=", value, "cocktailComment");
			return (Criteria) this;
		}

		public Criteria andCocktailCommentLessThan(String value) {
			addCriterion("cocktail_comment <", value, "cocktailComment");
			return (Criteria) this;
		}

		public Criteria andCocktailCommentLessThanOrEqualTo(String value) {
			addCriterion("cocktail_comment <=", value, "cocktailComment");
			return (Criteria) this;
		}

		public Criteria andCocktailCommentLike(String value) {
			addCriterion("cocktail_comment like", value, "cocktailComment");
			return (Criteria) this;
		}

		public Criteria andCocktailCommentNotLike(String value) {
			addCriterion("cocktail_comment not like", value, "cocktailComment");
			return (Criteria) this;
		}

		public Criteria andCocktailCommentIn(List<String> values) {
			addCriterion("cocktail_comment in", values, "cocktailComment");
			return (Criteria) this;
		}

		public Criteria andCocktailCommentNotIn(List<String> values) {
			addCriterion("cocktail_comment not in", values, "cocktailComment");
			return (Criteria) this;
		}

		public Criteria andCocktailCommentBetween(String value1, String value2) {
			addCriterion("cocktail_comment between", value1, value2, "cocktailComment");
			return (Criteria) this;
		}

		public Criteria andCocktailCommentNotBetween(String value1, String value2) {
			addCriterion("cocktail_comment not between", value1, value2, "cocktailComment");
			return (Criteria) this;
		}

		public Criteria andCocktailRatingIsNull() {
			addCriterion("cocktail_rating is null");
			return (Criteria) this;
		}

		public Criteria andCocktailRatingIsNotNull() {
			addCriterion("cocktail_rating is not null");
			return (Criteria) this;
		}

		public Criteria andCocktailRatingEqualTo(String value) {
			addCriterion("cocktail_rating =", value, "cocktailRating");
			return (Criteria) this;
		}

		public Criteria andCocktailRatingNotEqualTo(String value) {
			addCriterion("cocktail_rating <>", value, "cocktailRating");
			return (Criteria) this;
		}

		public Criteria andCocktailRatingGreaterThan(String value) {
			addCriterion("cocktail_rating >", value, "cocktailRating");
			return (Criteria) this;
		}

		public Criteria andCocktailRatingGreaterThanOrEqualTo(String value) {
			addCriterion("cocktail_rating >=", value, "cocktailRating");
			return (Criteria) this;
		}

		public Criteria andCocktailRatingLessThan(String value) {
			addCriterion("cocktail_rating <", value, "cocktailRating");
			return (Criteria) this;
		}

		public Criteria andCocktailRatingLessThanOrEqualTo(String value) {
			addCriterion("cocktail_rating <=", value, "cocktailRating");
			return (Criteria) this;
		}

		public Criteria andCocktailRatingLike(String value) {
			addCriterion("cocktail_rating like", value, "cocktailRating");
			return (Criteria) this;
		}

		public Criteria andCocktailRatingNotLike(String value) {
			addCriterion("cocktail_rating not like", value, "cocktailRating");
			return (Criteria) this;
		}

		public Criteria andCocktailRatingIn(List<String> values) {
			addCriterion("cocktail_rating in", values, "cocktailRating");
			return (Criteria) this;
		}

		public Criteria andCocktailRatingNotIn(List<String> values) {
			addCriterion("cocktail_rating not in", values, "cocktailRating");
			return (Criteria) this;
		}

		public Criteria andCocktailRatingBetween(String value1, String value2) {
			addCriterion("cocktail_rating between", value1, value2, "cocktailRating");
			return (Criteria) this;
		}

		public Criteria andCocktailRatingNotBetween(String value1, String value2) {
			addCriterion("cocktail_rating not between", value1, value2, "cocktailRating");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table cocktail
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cocktail
     *
     * @mbggenerated do_not_delete_during_merge Fri May 13 12:51:23 CDT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}