package com.roughindustries.commonwealthcocktails.mybatis.model;

public class Component {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column component.idcomponent
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private Integer idcomponent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column component.component_name
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private String componentName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column component.component_type
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private Integer componentType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column component.component_alternate_names
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private String componentAlternateNames;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column component.component_display_name
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private String componentDisplayName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column component.component_substitution
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private String componentSubstitution;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column component.component_echo_name
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private String componentEchoName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column component.component_image
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private String componentImage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column component.component_writeup
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private String componentWriteup;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column component.idcomponent
	 * @return  the value of component.idcomponent
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public Integer getIdcomponent() {
		return idcomponent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column component.idcomponent
	 * @param idcomponent  the value for component.idcomponent
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setIdcomponent(Integer idcomponent) {
		this.idcomponent = idcomponent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column component.component_name
	 * @return  the value of component.component_name
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public String getComponentName() {
		return componentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column component.component_name
	 * @param componentName  the value for component.component_name
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setComponentName(String componentName) {
		this.componentName = componentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column component.component_type
	 * @return  the value of component.component_type
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public Integer getComponentType() {
		return componentType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column component.component_type
	 * @param componentType  the value for component.component_type
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setComponentType(Integer componentType) {
		this.componentType = componentType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column component.component_alternate_names
	 * @return  the value of component.component_alternate_names
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public String getComponentAlternateNames() {
		return componentAlternateNames;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column component.component_alternate_names
	 * @param componentAlternateNames  the value for component.component_alternate_names
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setComponentAlternateNames(String componentAlternateNames) {
		this.componentAlternateNames = componentAlternateNames;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column component.component_display_name
	 * @return  the value of component.component_display_name
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public String getComponentDisplayName() {
		return componentDisplayName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column component.component_display_name
	 * @param componentDisplayName  the value for component.component_display_name
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setComponentDisplayName(String componentDisplayName) {
		this.componentDisplayName = componentDisplayName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column component.component_substitution
	 * @return  the value of component.component_substitution
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public String getComponentSubstitution() {
		return componentSubstitution;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column component.component_substitution
	 * @param componentSubstitution  the value for component.component_substitution
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setComponentSubstitution(String componentSubstitution) {
		this.componentSubstitution = componentSubstitution;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column component.component_echo_name
	 * @return  the value of component.component_echo_name
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public String getComponentEchoName() {
		return componentEchoName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column component.component_echo_name
	 * @param componentEchoName  the value for component.component_echo_name
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setComponentEchoName(String componentEchoName) {
		this.componentEchoName = componentEchoName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column component.component_image
	 * @return  the value of component.component_image
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public String getComponentImage() {
		return componentImage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column component.component_image
	 * @param componentImage  the value for component.component_image
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setComponentImage(String componentImage) {
		this.componentImage = componentImage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column component.component_writeup
	 * @return  the value of component.component_writeup
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public String getComponentWriteup() {
		return componentWriteup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column component.component_writeup
	 * @param componentWriteup  the value for component.component_writeup
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setComponentWriteup(String componentWriteup) {
		this.componentWriteup = componentWriteup;
	}
}