package com.roughindustries.commonwealthcocktails.mybatis.model;

public class Component2product {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column component2product.idcomponent2product
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private Integer idcomponent2product;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column component2product.component_id
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private Integer componentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column component2product.product_id
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private Integer productId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column component2product.note
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private String note;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column component2product.idcomponent2product
	 * @return  the value of component2product.idcomponent2product
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public Integer getIdcomponent2product() {
		return idcomponent2product;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column component2product.idcomponent2product
	 * @param idcomponent2product  the value for component2product.idcomponent2product
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setIdcomponent2product(Integer idcomponent2product) {
		this.idcomponent2product = idcomponent2product;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column component2product.component_id
	 * @return  the value of component2product.component_id
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public Integer getComponentId() {
		return componentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column component2product.component_id
	 * @param componentId  the value for component2product.component_id
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setComponentId(Integer componentId) {
		this.componentId = componentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column component2product.product_id
	 * @return  the value of component2product.product_id
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public Integer getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column component2product.product_id
	 * @param productId  the value for component2product.product_id
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column component2product.note
	 * @return  the value of component2product.note
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column component2product.note
	 * @param note  the value for component2product.note
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setNote(String note) {
		this.note = note;
	}
}