package com.roughindustries.commonwealthcocktails.mybatis.model;

public class Component2cocktail {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column component2cocktail.component_id
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private Integer componentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column component2cocktail.cocktail_id
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private Integer cocktailId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column component2cocktail.component_id
	 * @return  the value of component2cocktail.component_id
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public Integer getComponentId() {
		return componentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column component2cocktail.component_id
	 * @param componentId  the value for component2cocktail.component_id
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setComponentId(Integer componentId) {
		this.componentId = componentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column component2cocktail.cocktail_id
	 * @return  the value of component2cocktail.cocktail_id
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public Integer getCocktailId() {
		return cocktailId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column component2cocktail.cocktail_id
	 * @param cocktailId  the value for component2cocktail.cocktail_id
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setCocktailId(Integer cocktailId) {
		this.cocktailId = cocktailId;
	}
}