package com.roughindustries.commonwealthcocktails.mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class ComponentExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table component
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table component
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table component
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table component
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public ComponentExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table component
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table component
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table component
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table component
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table component
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table component
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table component
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table component
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table component
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table component
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table component
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdcomponentIsNull() {
			addCriterion("idcomponent is null");
			return (Criteria) this;
		}

		public Criteria andIdcomponentIsNotNull() {
			addCriterion("idcomponent is not null");
			return (Criteria) this;
		}

		public Criteria andIdcomponentEqualTo(Integer value) {
			addCriterion("idcomponent =", value, "idcomponent");
			return (Criteria) this;
		}

		public Criteria andIdcomponentNotEqualTo(Integer value) {
			addCriterion("idcomponent <>", value, "idcomponent");
			return (Criteria) this;
		}

		public Criteria andIdcomponentGreaterThan(Integer value) {
			addCriterion("idcomponent >", value, "idcomponent");
			return (Criteria) this;
		}

		public Criteria andIdcomponentGreaterThanOrEqualTo(Integer value) {
			addCriterion("idcomponent >=", value, "idcomponent");
			return (Criteria) this;
		}

		public Criteria andIdcomponentLessThan(Integer value) {
			addCriterion("idcomponent <", value, "idcomponent");
			return (Criteria) this;
		}

		public Criteria andIdcomponentLessThanOrEqualTo(Integer value) {
			addCriterion("idcomponent <=", value, "idcomponent");
			return (Criteria) this;
		}

		public Criteria andIdcomponentIn(List<Integer> values) {
			addCriterion("idcomponent in", values, "idcomponent");
			return (Criteria) this;
		}

		public Criteria andIdcomponentNotIn(List<Integer> values) {
			addCriterion("idcomponent not in", values, "idcomponent");
			return (Criteria) this;
		}

		public Criteria andIdcomponentBetween(Integer value1, Integer value2) {
			addCriterion("idcomponent between", value1, value2, "idcomponent");
			return (Criteria) this;
		}

		public Criteria andIdcomponentNotBetween(Integer value1, Integer value2) {
			addCriterion("idcomponent not between", value1, value2, "idcomponent");
			return (Criteria) this;
		}

		public Criteria andComponentNameIsNull() {
			addCriterion("component_name is null");
			return (Criteria) this;
		}

		public Criteria andComponentNameIsNotNull() {
			addCriterion("component_name is not null");
			return (Criteria) this;
		}

		public Criteria andComponentNameEqualTo(String value) {
			addCriterion("component_name =", value, "componentName");
			return (Criteria) this;
		}

		public Criteria andComponentNameNotEqualTo(String value) {
			addCriterion("component_name <>", value, "componentName");
			return (Criteria) this;
		}

		public Criteria andComponentNameGreaterThan(String value) {
			addCriterion("component_name >", value, "componentName");
			return (Criteria) this;
		}

		public Criteria andComponentNameGreaterThanOrEqualTo(String value) {
			addCriterion("component_name >=", value, "componentName");
			return (Criteria) this;
		}

		public Criteria andComponentNameLessThan(String value) {
			addCriterion("component_name <", value, "componentName");
			return (Criteria) this;
		}

		public Criteria andComponentNameLessThanOrEqualTo(String value) {
			addCriterion("component_name <=", value, "componentName");
			return (Criteria) this;
		}

		public Criteria andComponentNameLike(String value) {
			addCriterion("component_name like", value, "componentName");
			return (Criteria) this;
		}

		public Criteria andComponentNameNotLike(String value) {
			addCriterion("component_name not like", value, "componentName");
			return (Criteria) this;
		}

		public Criteria andComponentNameIn(List<String> values) {
			addCriterion("component_name in", values, "componentName");
			return (Criteria) this;
		}

		public Criteria andComponentNameNotIn(List<String> values) {
			addCriterion("component_name not in", values, "componentName");
			return (Criteria) this;
		}

		public Criteria andComponentNameBetween(String value1, String value2) {
			addCriterion("component_name between", value1, value2, "componentName");
			return (Criteria) this;
		}

		public Criteria andComponentNameNotBetween(String value1, String value2) {
			addCriterion("component_name not between", value1, value2, "componentName");
			return (Criteria) this;
		}

		public Criteria andComponentTypeIsNull() {
			addCriterion("component_type is null");
			return (Criteria) this;
		}

		public Criteria andComponentTypeIsNotNull() {
			addCriterion("component_type is not null");
			return (Criteria) this;
		}

		public Criteria andComponentTypeEqualTo(Integer value) {
			addCriterion("component_type =", value, "componentType");
			return (Criteria) this;
		}

		public Criteria andComponentTypeNotEqualTo(Integer value) {
			addCriterion("component_type <>", value, "componentType");
			return (Criteria) this;
		}

		public Criteria andComponentTypeGreaterThan(Integer value) {
			addCriterion("component_type >", value, "componentType");
			return (Criteria) this;
		}

		public Criteria andComponentTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("component_type >=", value, "componentType");
			return (Criteria) this;
		}

		public Criteria andComponentTypeLessThan(Integer value) {
			addCriterion("component_type <", value, "componentType");
			return (Criteria) this;
		}

		public Criteria andComponentTypeLessThanOrEqualTo(Integer value) {
			addCriterion("component_type <=", value, "componentType");
			return (Criteria) this;
		}

		public Criteria andComponentTypeIn(List<Integer> values) {
			addCriterion("component_type in", values, "componentType");
			return (Criteria) this;
		}

		public Criteria andComponentTypeNotIn(List<Integer> values) {
			addCriterion("component_type not in", values, "componentType");
			return (Criteria) this;
		}

		public Criteria andComponentTypeBetween(Integer value1, Integer value2) {
			addCriterion("component_type between", value1, value2, "componentType");
			return (Criteria) this;
		}

		public Criteria andComponentTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("component_type not between", value1, value2, "componentType");
			return (Criteria) this;
		}

		public Criteria andComponentAlternateNamesIsNull() {
			addCriterion("component_alternate_names is null");
			return (Criteria) this;
		}

		public Criteria andComponentAlternateNamesIsNotNull() {
			addCriterion("component_alternate_names is not null");
			return (Criteria) this;
		}

		public Criteria andComponentAlternateNamesEqualTo(String value) {
			addCriterion("component_alternate_names =", value, "componentAlternateNames");
			return (Criteria) this;
		}

		public Criteria andComponentAlternateNamesNotEqualTo(String value) {
			addCriterion("component_alternate_names <>", value, "componentAlternateNames");
			return (Criteria) this;
		}

		public Criteria andComponentAlternateNamesGreaterThan(String value) {
			addCriterion("component_alternate_names >", value, "componentAlternateNames");
			return (Criteria) this;
		}

		public Criteria andComponentAlternateNamesGreaterThanOrEqualTo(String value) {
			addCriterion("component_alternate_names >=", value, "componentAlternateNames");
			return (Criteria) this;
		}

		public Criteria andComponentAlternateNamesLessThan(String value) {
			addCriterion("component_alternate_names <", value, "componentAlternateNames");
			return (Criteria) this;
		}

		public Criteria andComponentAlternateNamesLessThanOrEqualTo(String value) {
			addCriterion("component_alternate_names <=", value, "componentAlternateNames");
			return (Criteria) this;
		}

		public Criteria andComponentAlternateNamesLike(String value) {
			addCriterion("component_alternate_names like", value, "componentAlternateNames");
			return (Criteria) this;
		}

		public Criteria andComponentAlternateNamesNotLike(String value) {
			addCriterion("component_alternate_names not like", value, "componentAlternateNames");
			return (Criteria) this;
		}

		public Criteria andComponentAlternateNamesIn(List<String> values) {
			addCriterion("component_alternate_names in", values, "componentAlternateNames");
			return (Criteria) this;
		}

		public Criteria andComponentAlternateNamesNotIn(List<String> values) {
			addCriterion("component_alternate_names not in", values, "componentAlternateNames");
			return (Criteria) this;
		}

		public Criteria andComponentAlternateNamesBetween(String value1, String value2) {
			addCriterion("component_alternate_names between", value1, value2, "componentAlternateNames");
			return (Criteria) this;
		}

		public Criteria andComponentAlternateNamesNotBetween(String value1, String value2) {
			addCriterion("component_alternate_names not between", value1, value2, "componentAlternateNames");
			return (Criteria) this;
		}

		public Criteria andComponentDisplayNameIsNull() {
			addCriterion("component_display_name is null");
			return (Criteria) this;
		}

		public Criteria andComponentDisplayNameIsNotNull() {
			addCriterion("component_display_name is not null");
			return (Criteria) this;
		}

		public Criteria andComponentDisplayNameEqualTo(String value) {
			addCriterion("component_display_name =", value, "componentDisplayName");
			return (Criteria) this;
		}

		public Criteria andComponentDisplayNameNotEqualTo(String value) {
			addCriterion("component_display_name <>", value, "componentDisplayName");
			return (Criteria) this;
		}

		public Criteria andComponentDisplayNameGreaterThan(String value) {
			addCriterion("component_display_name >", value, "componentDisplayName");
			return (Criteria) this;
		}

		public Criteria andComponentDisplayNameGreaterThanOrEqualTo(String value) {
			addCriterion("component_display_name >=", value, "componentDisplayName");
			return (Criteria) this;
		}

		public Criteria andComponentDisplayNameLessThan(String value) {
			addCriterion("component_display_name <", value, "componentDisplayName");
			return (Criteria) this;
		}

		public Criteria andComponentDisplayNameLessThanOrEqualTo(String value) {
			addCriterion("component_display_name <=", value, "componentDisplayName");
			return (Criteria) this;
		}

		public Criteria andComponentDisplayNameLike(String value) {
			addCriterion("component_display_name like", value, "componentDisplayName");
			return (Criteria) this;
		}

		public Criteria andComponentDisplayNameNotLike(String value) {
			addCriterion("component_display_name not like", value, "componentDisplayName");
			return (Criteria) this;
		}

		public Criteria andComponentDisplayNameIn(List<String> values) {
			addCriterion("component_display_name in", values, "componentDisplayName");
			return (Criteria) this;
		}

		public Criteria andComponentDisplayNameNotIn(List<String> values) {
			addCriterion("component_display_name not in", values, "componentDisplayName");
			return (Criteria) this;
		}

		public Criteria andComponentDisplayNameBetween(String value1, String value2) {
			addCriterion("component_display_name between", value1, value2, "componentDisplayName");
			return (Criteria) this;
		}

		public Criteria andComponentDisplayNameNotBetween(String value1, String value2) {
			addCriterion("component_display_name not between", value1, value2, "componentDisplayName");
			return (Criteria) this;
		}

		public Criteria andComponentSubstitutionIsNull() {
			addCriterion("component_substitution is null");
			return (Criteria) this;
		}

		public Criteria andComponentSubstitutionIsNotNull() {
			addCriterion("component_substitution is not null");
			return (Criteria) this;
		}

		public Criteria andComponentSubstitutionEqualTo(String value) {
			addCriterion("component_substitution =", value, "componentSubstitution");
			return (Criteria) this;
		}

		public Criteria andComponentSubstitutionNotEqualTo(String value) {
			addCriterion("component_substitution <>", value, "componentSubstitution");
			return (Criteria) this;
		}

		public Criteria andComponentSubstitutionGreaterThan(String value) {
			addCriterion("component_substitution >", value, "componentSubstitution");
			return (Criteria) this;
		}

		public Criteria andComponentSubstitutionGreaterThanOrEqualTo(String value) {
			addCriterion("component_substitution >=", value, "componentSubstitution");
			return (Criteria) this;
		}

		public Criteria andComponentSubstitutionLessThan(String value) {
			addCriterion("component_substitution <", value, "componentSubstitution");
			return (Criteria) this;
		}

		public Criteria andComponentSubstitutionLessThanOrEqualTo(String value) {
			addCriterion("component_substitution <=", value, "componentSubstitution");
			return (Criteria) this;
		}

		public Criteria andComponentSubstitutionLike(String value) {
			addCriterion("component_substitution like", value, "componentSubstitution");
			return (Criteria) this;
		}

		public Criteria andComponentSubstitutionNotLike(String value) {
			addCriterion("component_substitution not like", value, "componentSubstitution");
			return (Criteria) this;
		}

		public Criteria andComponentSubstitutionIn(List<String> values) {
			addCriterion("component_substitution in", values, "componentSubstitution");
			return (Criteria) this;
		}

		public Criteria andComponentSubstitutionNotIn(List<String> values) {
			addCriterion("component_substitution not in", values, "componentSubstitution");
			return (Criteria) this;
		}

		public Criteria andComponentSubstitutionBetween(String value1, String value2) {
			addCriterion("component_substitution between", value1, value2, "componentSubstitution");
			return (Criteria) this;
		}

		public Criteria andComponentSubstitutionNotBetween(String value1, String value2) {
			addCriterion("component_substitution not between", value1, value2, "componentSubstitution");
			return (Criteria) this;
		}

		public Criteria andComponentEchoNameIsNull() {
			addCriterion("component_echo_name is null");
			return (Criteria) this;
		}

		public Criteria andComponentEchoNameIsNotNull() {
			addCriterion("component_echo_name is not null");
			return (Criteria) this;
		}

		public Criteria andComponentEchoNameEqualTo(String value) {
			addCriterion("component_echo_name =", value, "componentEchoName");
			return (Criteria) this;
		}

		public Criteria andComponentEchoNameNotEqualTo(String value) {
			addCriterion("component_echo_name <>", value, "componentEchoName");
			return (Criteria) this;
		}

		public Criteria andComponentEchoNameGreaterThan(String value) {
			addCriterion("component_echo_name >", value, "componentEchoName");
			return (Criteria) this;
		}

		public Criteria andComponentEchoNameGreaterThanOrEqualTo(String value) {
			addCriterion("component_echo_name >=", value, "componentEchoName");
			return (Criteria) this;
		}

		public Criteria andComponentEchoNameLessThan(String value) {
			addCriterion("component_echo_name <", value, "componentEchoName");
			return (Criteria) this;
		}

		public Criteria andComponentEchoNameLessThanOrEqualTo(String value) {
			addCriterion("component_echo_name <=", value, "componentEchoName");
			return (Criteria) this;
		}

		public Criteria andComponentEchoNameLike(String value) {
			addCriterion("component_echo_name like", value, "componentEchoName");
			return (Criteria) this;
		}

		public Criteria andComponentEchoNameNotLike(String value) {
			addCriterion("component_echo_name not like", value, "componentEchoName");
			return (Criteria) this;
		}

		public Criteria andComponentEchoNameIn(List<String> values) {
			addCriterion("component_echo_name in", values, "componentEchoName");
			return (Criteria) this;
		}

		public Criteria andComponentEchoNameNotIn(List<String> values) {
			addCriterion("component_echo_name not in", values, "componentEchoName");
			return (Criteria) this;
		}

		public Criteria andComponentEchoNameBetween(String value1, String value2) {
			addCriterion("component_echo_name between", value1, value2, "componentEchoName");
			return (Criteria) this;
		}

		public Criteria andComponentEchoNameNotBetween(String value1, String value2) {
			addCriterion("component_echo_name not between", value1, value2, "componentEchoName");
			return (Criteria) this;
		}

		public Criteria andComponentImageIsNull() {
			addCriterion("component_image is null");
			return (Criteria) this;
		}

		public Criteria andComponentImageIsNotNull() {
			addCriterion("component_image is not null");
			return (Criteria) this;
		}

		public Criteria andComponentImageEqualTo(String value) {
			addCriterion("component_image =", value, "componentImage");
			return (Criteria) this;
		}

		public Criteria andComponentImageNotEqualTo(String value) {
			addCriterion("component_image <>", value, "componentImage");
			return (Criteria) this;
		}

		public Criteria andComponentImageGreaterThan(String value) {
			addCriterion("component_image >", value, "componentImage");
			return (Criteria) this;
		}

		public Criteria andComponentImageGreaterThanOrEqualTo(String value) {
			addCriterion("component_image >=", value, "componentImage");
			return (Criteria) this;
		}

		public Criteria andComponentImageLessThan(String value) {
			addCriterion("component_image <", value, "componentImage");
			return (Criteria) this;
		}

		public Criteria andComponentImageLessThanOrEqualTo(String value) {
			addCriterion("component_image <=", value, "componentImage");
			return (Criteria) this;
		}

		public Criteria andComponentImageLike(String value) {
			addCriterion("component_image like", value, "componentImage");
			return (Criteria) this;
		}

		public Criteria andComponentImageNotLike(String value) {
			addCriterion("component_image not like", value, "componentImage");
			return (Criteria) this;
		}

		public Criteria andComponentImageIn(List<String> values) {
			addCriterion("component_image in", values, "componentImage");
			return (Criteria) this;
		}

		public Criteria andComponentImageNotIn(List<String> values) {
			addCriterion("component_image not in", values, "componentImage");
			return (Criteria) this;
		}

		public Criteria andComponentImageBetween(String value1, String value2) {
			addCriterion("component_image between", value1, value2, "componentImage");
			return (Criteria) this;
		}

		public Criteria andComponentImageNotBetween(String value1, String value2) {
			addCriterion("component_image not between", value1, value2, "componentImage");
			return (Criteria) this;
		}

		public Criteria andComponentWriteupIsNull() {
			addCriterion("component_writeup is null");
			return (Criteria) this;
		}

		public Criteria andComponentWriteupIsNotNull() {
			addCriterion("component_writeup is not null");
			return (Criteria) this;
		}

		public Criteria andComponentWriteupEqualTo(String value) {
			addCriterion("component_writeup =", value, "componentWriteup");
			return (Criteria) this;
		}

		public Criteria andComponentWriteupNotEqualTo(String value) {
			addCriterion("component_writeup <>", value, "componentWriteup");
			return (Criteria) this;
		}

		public Criteria andComponentWriteupGreaterThan(String value) {
			addCriterion("component_writeup >", value, "componentWriteup");
			return (Criteria) this;
		}

		public Criteria andComponentWriteupGreaterThanOrEqualTo(String value) {
			addCriterion("component_writeup >=", value, "componentWriteup");
			return (Criteria) this;
		}

		public Criteria andComponentWriteupLessThan(String value) {
			addCriterion("component_writeup <", value, "componentWriteup");
			return (Criteria) this;
		}

		public Criteria andComponentWriteupLessThanOrEqualTo(String value) {
			addCriterion("component_writeup <=", value, "componentWriteup");
			return (Criteria) this;
		}

		public Criteria andComponentWriteupLike(String value) {
			addCriterion("component_writeup like", value, "componentWriteup");
			return (Criteria) this;
		}

		public Criteria andComponentWriteupNotLike(String value) {
			addCriterion("component_writeup not like", value, "componentWriteup");
			return (Criteria) this;
		}

		public Criteria andComponentWriteupIn(List<String> values) {
			addCriterion("component_writeup in", values, "componentWriteup");
			return (Criteria) this;
		}

		public Criteria andComponentWriteupNotIn(List<String> values) {
			addCriterion("component_writeup not in", values, "componentWriteup");
			return (Criteria) this;
		}

		public Criteria andComponentWriteupBetween(String value1, String value2) {
			addCriterion("component_writeup between", value1, value2, "componentWriteup");
			return (Criteria) this;
		}

		public Criteria andComponentWriteupNotBetween(String value1, String value2) {
			addCriterion("component_writeup not between", value1, value2, "componentWriteup");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table component
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table component
     *
     * @mbggenerated do_not_delete_during_merge Fri May 13 12:51:23 CDT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}