package com.roughindustries.commonwealthcocktails.mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class ProductExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table product
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table product
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table product
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public ProductExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table product
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdproductsIsNull() {
			addCriterion("idproducts is null");
			return (Criteria) this;
		}

		public Criteria andIdproductsIsNotNull() {
			addCriterion("idproducts is not null");
			return (Criteria) this;
		}

		public Criteria andIdproductsEqualTo(Integer value) {
			addCriterion("idproducts =", value, "idproducts");
			return (Criteria) this;
		}

		public Criteria andIdproductsNotEqualTo(Integer value) {
			addCriterion("idproducts <>", value, "idproducts");
			return (Criteria) this;
		}

		public Criteria andIdproductsGreaterThan(Integer value) {
			addCriterion("idproducts >", value, "idproducts");
			return (Criteria) this;
		}

		public Criteria andIdproductsGreaterThanOrEqualTo(Integer value) {
			addCriterion("idproducts >=", value, "idproducts");
			return (Criteria) this;
		}

		public Criteria andIdproductsLessThan(Integer value) {
			addCriterion("idproducts <", value, "idproducts");
			return (Criteria) this;
		}

		public Criteria andIdproductsLessThanOrEqualTo(Integer value) {
			addCriterion("idproducts <=", value, "idproducts");
			return (Criteria) this;
		}

		public Criteria andIdproductsIn(List<Integer> values) {
			addCriterion("idproducts in", values, "idproducts");
			return (Criteria) this;
		}

		public Criteria andIdproductsNotIn(List<Integer> values) {
			addCriterion("idproducts not in", values, "idproducts");
			return (Criteria) this;
		}

		public Criteria andIdproductsBetween(Integer value1, Integer value2) {
			addCriterion("idproducts between", value1, value2, "idproducts");
			return (Criteria) this;
		}

		public Criteria andIdproductsNotBetween(Integer value1, Integer value2) {
			addCriterion("idproducts not between", value1, value2, "idproducts");
			return (Criteria) this;
		}

		public Criteria andProductNameIsNull() {
			addCriterion("product_name is null");
			return (Criteria) this;
		}

		public Criteria andProductNameIsNotNull() {
			addCriterion("product_name is not null");
			return (Criteria) this;
		}

		public Criteria andProductNameEqualTo(String value) {
			addCriterion("product_name =", value, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameNotEqualTo(String value) {
			addCriterion("product_name <>", value, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameGreaterThan(String value) {
			addCriterion("product_name >", value, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameGreaterThanOrEqualTo(String value) {
			addCriterion("product_name >=", value, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameLessThan(String value) {
			addCriterion("product_name <", value, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameLessThanOrEqualTo(String value) {
			addCriterion("product_name <=", value, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameLike(String value) {
			addCriterion("product_name like", value, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameNotLike(String value) {
			addCriterion("product_name not like", value, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameIn(List<String> values) {
			addCriterion("product_name in", values, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameNotIn(List<String> values) {
			addCriterion("product_name not in", values, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameBetween(String value1, String value2) {
			addCriterion("product_name between", value1, value2, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameNotBetween(String value1, String value2) {
			addCriterion("product_name not between", value1, value2, "productName");
			return (Criteria) this;
		}

		public Criteria andProductWebsiteIsNull() {
			addCriterion("product_website is null");
			return (Criteria) this;
		}

		public Criteria andProductWebsiteIsNotNull() {
			addCriterion("product_website is not null");
			return (Criteria) this;
		}

		public Criteria andProductWebsiteEqualTo(String value) {
			addCriterion("product_website =", value, "productWebsite");
			return (Criteria) this;
		}

		public Criteria andProductWebsiteNotEqualTo(String value) {
			addCriterion("product_website <>", value, "productWebsite");
			return (Criteria) this;
		}

		public Criteria andProductWebsiteGreaterThan(String value) {
			addCriterion("product_website >", value, "productWebsite");
			return (Criteria) this;
		}

		public Criteria andProductWebsiteGreaterThanOrEqualTo(String value) {
			addCriterion("product_website >=", value, "productWebsite");
			return (Criteria) this;
		}

		public Criteria andProductWebsiteLessThan(String value) {
			addCriterion("product_website <", value, "productWebsite");
			return (Criteria) this;
		}

		public Criteria andProductWebsiteLessThanOrEqualTo(String value) {
			addCriterion("product_website <=", value, "productWebsite");
			return (Criteria) this;
		}

		public Criteria andProductWebsiteLike(String value) {
			addCriterion("product_website like", value, "productWebsite");
			return (Criteria) this;
		}

		public Criteria andProductWebsiteNotLike(String value) {
			addCriterion("product_website not like", value, "productWebsite");
			return (Criteria) this;
		}

		public Criteria andProductWebsiteIn(List<String> values) {
			addCriterion("product_website in", values, "productWebsite");
			return (Criteria) this;
		}

		public Criteria andProductWebsiteNotIn(List<String> values) {
			addCriterion("product_website not in", values, "productWebsite");
			return (Criteria) this;
		}

		public Criteria andProductWebsiteBetween(String value1, String value2) {
			addCriterion("product_website between", value1, value2, "productWebsite");
			return (Criteria) this;
		}

		public Criteria andProductWebsiteNotBetween(String value1, String value2) {
			addCriterion("product_website not between", value1, value2, "productWebsite");
			return (Criteria) this;
		}

		public Criteria andProductProducerIsNull() {
			addCriterion("product_producer is null");
			return (Criteria) this;
		}

		public Criteria andProductProducerIsNotNull() {
			addCriterion("product_producer is not null");
			return (Criteria) this;
		}

		public Criteria andProductProducerEqualTo(Integer value) {
			addCriterion("product_producer =", value, "productProducer");
			return (Criteria) this;
		}

		public Criteria andProductProducerNotEqualTo(Integer value) {
			addCriterion("product_producer <>", value, "productProducer");
			return (Criteria) this;
		}

		public Criteria andProductProducerGreaterThan(Integer value) {
			addCriterion("product_producer >", value, "productProducer");
			return (Criteria) this;
		}

		public Criteria andProductProducerGreaterThanOrEqualTo(Integer value) {
			addCriterion("product_producer >=", value, "productProducer");
			return (Criteria) this;
		}

		public Criteria andProductProducerLessThan(Integer value) {
			addCriterion("product_producer <", value, "productProducer");
			return (Criteria) this;
		}

		public Criteria andProductProducerLessThanOrEqualTo(Integer value) {
			addCriterion("product_producer <=", value, "productProducer");
			return (Criteria) this;
		}

		public Criteria andProductProducerIn(List<Integer> values) {
			addCriterion("product_producer in", values, "productProducer");
			return (Criteria) this;
		}

		public Criteria andProductProducerNotIn(List<Integer> values) {
			addCriterion("product_producer not in", values, "productProducer");
			return (Criteria) this;
		}

		public Criteria andProductProducerBetween(Integer value1, Integer value2) {
			addCriterion("product_producer between", value1, value2, "productProducer");
			return (Criteria) this;
		}

		public Criteria andProductProducerNotBetween(Integer value1, Integer value2) {
			addCriterion("product_producer not between", value1, value2, "productProducer");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table product
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbggenerated do_not_delete_during_merge Fri May 13 12:51:23 CDT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}