package com.roughindustries.commonwealthcocktails.mybatis.model;

public class Product {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.idproducts
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private Integer idproducts;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.product_name
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private String productName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.product_website
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private String productWebsite;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.product_producer
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private Integer productProducer;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.idproducts
	 * @return  the value of product.idproducts
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public Integer getIdproducts() {
		return idproducts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.idproducts
	 * @param idproducts  the value for product.idproducts
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setIdproducts(Integer idproducts) {
		this.idproducts = idproducts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.product_name
	 * @return  the value of product.product_name
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public String getProductName() {
		return productName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.product_name
	 * @param productName  the value for product.product_name
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setProductName(String productName) {
		this.productName = productName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.product_website
	 * @return  the value of product.product_website
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public String getProductWebsite() {
		return productWebsite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.product_website
	 * @param productWebsite  the value for product.product_website
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setProductWebsite(String productWebsite) {
		this.productWebsite = productWebsite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.product_producer
	 * @return  the value of product.product_producer
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public Integer getProductProducer() {
		return productProducer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.product_producer
	 * @param productProducer  the value for product.product_producer
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setProductProducer(Integer productProducer) {
		this.productProducer = productProducer;
	}
}