package com.roughindustries.commonwealthcocktails.mybatis.model;

public class Producer {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producer.idproducer
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private Integer idproducer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producer.producer_name
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private String producerName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producer.producer_location
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private String producerLocation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producer.producer_telephonel
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private String producerTelephonel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producer.producer_website
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private String producerWebsite;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producer.idproducer
	 * @return  the value of producer.idproducer
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public Integer getIdproducer() {
		return idproducer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producer.idproducer
	 * @param idproducer  the value for producer.idproducer
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setIdproducer(Integer idproducer) {
		this.idproducer = idproducer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producer.producer_name
	 * @return  the value of producer.producer_name
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public String getProducerName() {
		return producerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producer.producer_name
	 * @param producerName  the value for producer.producer_name
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setProducerName(String producerName) {
		this.producerName = producerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producer.producer_location
	 * @return  the value of producer.producer_location
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public String getProducerLocation() {
		return producerLocation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producer.producer_location
	 * @param producerLocation  the value for producer.producer_location
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setProducerLocation(String producerLocation) {
		this.producerLocation = producerLocation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producer.producer_telephonel
	 * @return  the value of producer.producer_telephonel
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public String getProducerTelephonel() {
		return producerTelephonel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producer.producer_telephonel
	 * @param producerTelephonel  the value for producer.producer_telephonel
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setProducerTelephonel(String producerTelephonel) {
		this.producerTelephonel = producerTelephonel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producer.producer_website
	 * @return  the value of producer.producer_website
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public String getProducerWebsite() {
		return producerWebsite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producer.producer_website
	 * @param producerWebsite  the value for producer.producer_website
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setProducerWebsite(String producerWebsite) {
		this.producerWebsite = producerWebsite;
	}
}