package com.roughindustries.commonwealthcocktails.mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class ProducerExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table producer
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table producer
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table producer
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producer
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public ProducerExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producer
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producer
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producer
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producer
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producer
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producer
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producer
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producer
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producer
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producer
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table producer
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdproducerIsNull() {
			addCriterion("idproducer is null");
			return (Criteria) this;
		}

		public Criteria andIdproducerIsNotNull() {
			addCriterion("idproducer is not null");
			return (Criteria) this;
		}

		public Criteria andIdproducerEqualTo(Integer value) {
			addCriterion("idproducer =", value, "idproducer");
			return (Criteria) this;
		}

		public Criteria andIdproducerNotEqualTo(Integer value) {
			addCriterion("idproducer <>", value, "idproducer");
			return (Criteria) this;
		}

		public Criteria andIdproducerGreaterThan(Integer value) {
			addCriterion("idproducer >", value, "idproducer");
			return (Criteria) this;
		}

		public Criteria andIdproducerGreaterThanOrEqualTo(Integer value) {
			addCriterion("idproducer >=", value, "idproducer");
			return (Criteria) this;
		}

		public Criteria andIdproducerLessThan(Integer value) {
			addCriterion("idproducer <", value, "idproducer");
			return (Criteria) this;
		}

		public Criteria andIdproducerLessThanOrEqualTo(Integer value) {
			addCriterion("idproducer <=", value, "idproducer");
			return (Criteria) this;
		}

		public Criteria andIdproducerIn(List<Integer> values) {
			addCriterion("idproducer in", values, "idproducer");
			return (Criteria) this;
		}

		public Criteria andIdproducerNotIn(List<Integer> values) {
			addCriterion("idproducer not in", values, "idproducer");
			return (Criteria) this;
		}

		public Criteria andIdproducerBetween(Integer value1, Integer value2) {
			addCriterion("idproducer between", value1, value2, "idproducer");
			return (Criteria) this;
		}

		public Criteria andIdproducerNotBetween(Integer value1, Integer value2) {
			addCriterion("idproducer not between", value1, value2, "idproducer");
			return (Criteria) this;
		}

		public Criteria andProducerNameIsNull() {
			addCriterion("producer_name is null");
			return (Criteria) this;
		}

		public Criteria andProducerNameIsNotNull() {
			addCriterion("producer_name is not null");
			return (Criteria) this;
		}

		public Criteria andProducerNameEqualTo(String value) {
			addCriterion("producer_name =", value, "producerName");
			return (Criteria) this;
		}

		public Criteria andProducerNameNotEqualTo(String value) {
			addCriterion("producer_name <>", value, "producerName");
			return (Criteria) this;
		}

		public Criteria andProducerNameGreaterThan(String value) {
			addCriterion("producer_name >", value, "producerName");
			return (Criteria) this;
		}

		public Criteria andProducerNameGreaterThanOrEqualTo(String value) {
			addCriterion("producer_name >=", value, "producerName");
			return (Criteria) this;
		}

		public Criteria andProducerNameLessThan(String value) {
			addCriterion("producer_name <", value, "producerName");
			return (Criteria) this;
		}

		public Criteria andProducerNameLessThanOrEqualTo(String value) {
			addCriterion("producer_name <=", value, "producerName");
			return (Criteria) this;
		}

		public Criteria andProducerNameLike(String value) {
			addCriterion("producer_name like", value, "producerName");
			return (Criteria) this;
		}

		public Criteria andProducerNameNotLike(String value) {
			addCriterion("producer_name not like", value, "producerName");
			return (Criteria) this;
		}

		public Criteria andProducerNameIn(List<String> values) {
			addCriterion("producer_name in", values, "producerName");
			return (Criteria) this;
		}

		public Criteria andProducerNameNotIn(List<String> values) {
			addCriterion("producer_name not in", values, "producerName");
			return (Criteria) this;
		}

		public Criteria andProducerNameBetween(String value1, String value2) {
			addCriterion("producer_name between", value1, value2, "producerName");
			return (Criteria) this;
		}

		public Criteria andProducerNameNotBetween(String value1, String value2) {
			addCriterion("producer_name not between", value1, value2, "producerName");
			return (Criteria) this;
		}

		public Criteria andProducerLocationIsNull() {
			addCriterion("producer_location is null");
			return (Criteria) this;
		}

		public Criteria andProducerLocationIsNotNull() {
			addCriterion("producer_location is not null");
			return (Criteria) this;
		}

		public Criteria andProducerLocationEqualTo(String value) {
			addCriterion("producer_location =", value, "producerLocation");
			return (Criteria) this;
		}

		public Criteria andProducerLocationNotEqualTo(String value) {
			addCriterion("producer_location <>", value, "producerLocation");
			return (Criteria) this;
		}

		public Criteria andProducerLocationGreaterThan(String value) {
			addCriterion("producer_location >", value, "producerLocation");
			return (Criteria) this;
		}

		public Criteria andProducerLocationGreaterThanOrEqualTo(String value) {
			addCriterion("producer_location >=", value, "producerLocation");
			return (Criteria) this;
		}

		public Criteria andProducerLocationLessThan(String value) {
			addCriterion("producer_location <", value, "producerLocation");
			return (Criteria) this;
		}

		public Criteria andProducerLocationLessThanOrEqualTo(String value) {
			addCriterion("producer_location <=", value, "producerLocation");
			return (Criteria) this;
		}

		public Criteria andProducerLocationLike(String value) {
			addCriterion("producer_location like", value, "producerLocation");
			return (Criteria) this;
		}

		public Criteria andProducerLocationNotLike(String value) {
			addCriterion("producer_location not like", value, "producerLocation");
			return (Criteria) this;
		}

		public Criteria andProducerLocationIn(List<String> values) {
			addCriterion("producer_location in", values, "producerLocation");
			return (Criteria) this;
		}

		public Criteria andProducerLocationNotIn(List<String> values) {
			addCriterion("producer_location not in", values, "producerLocation");
			return (Criteria) this;
		}

		public Criteria andProducerLocationBetween(String value1, String value2) {
			addCriterion("producer_location between", value1, value2, "producerLocation");
			return (Criteria) this;
		}

		public Criteria andProducerLocationNotBetween(String value1, String value2) {
			addCriterion("producer_location not between", value1, value2, "producerLocation");
			return (Criteria) this;
		}

		public Criteria andProducerTelephonelIsNull() {
			addCriterion("producer_telephonel is null");
			return (Criteria) this;
		}

		public Criteria andProducerTelephonelIsNotNull() {
			addCriterion("producer_telephonel is not null");
			return (Criteria) this;
		}

		public Criteria andProducerTelephonelEqualTo(String value) {
			addCriterion("producer_telephonel =", value, "producerTelephonel");
			return (Criteria) this;
		}

		public Criteria andProducerTelephonelNotEqualTo(String value) {
			addCriterion("producer_telephonel <>", value, "producerTelephonel");
			return (Criteria) this;
		}

		public Criteria andProducerTelephonelGreaterThan(String value) {
			addCriterion("producer_telephonel >", value, "producerTelephonel");
			return (Criteria) this;
		}

		public Criteria andProducerTelephonelGreaterThanOrEqualTo(String value) {
			addCriterion("producer_telephonel >=", value, "producerTelephonel");
			return (Criteria) this;
		}

		public Criteria andProducerTelephonelLessThan(String value) {
			addCriterion("producer_telephonel <", value, "producerTelephonel");
			return (Criteria) this;
		}

		public Criteria andProducerTelephonelLessThanOrEqualTo(String value) {
			addCriterion("producer_telephonel <=", value, "producerTelephonel");
			return (Criteria) this;
		}

		public Criteria andProducerTelephonelLike(String value) {
			addCriterion("producer_telephonel like", value, "producerTelephonel");
			return (Criteria) this;
		}

		public Criteria andProducerTelephonelNotLike(String value) {
			addCriterion("producer_telephonel not like", value, "producerTelephonel");
			return (Criteria) this;
		}

		public Criteria andProducerTelephonelIn(List<String> values) {
			addCriterion("producer_telephonel in", values, "producerTelephonel");
			return (Criteria) this;
		}

		public Criteria andProducerTelephonelNotIn(List<String> values) {
			addCriterion("producer_telephonel not in", values, "producerTelephonel");
			return (Criteria) this;
		}

		public Criteria andProducerTelephonelBetween(String value1, String value2) {
			addCriterion("producer_telephonel between", value1, value2, "producerTelephonel");
			return (Criteria) this;
		}

		public Criteria andProducerTelephonelNotBetween(String value1, String value2) {
			addCriterion("producer_telephonel not between", value1, value2, "producerTelephonel");
			return (Criteria) this;
		}

		public Criteria andProducerWebsiteIsNull() {
			addCriterion("producer_website is null");
			return (Criteria) this;
		}

		public Criteria andProducerWebsiteIsNotNull() {
			addCriterion("producer_website is not null");
			return (Criteria) this;
		}

		public Criteria andProducerWebsiteEqualTo(String value) {
			addCriterion("producer_website =", value, "producerWebsite");
			return (Criteria) this;
		}

		public Criteria andProducerWebsiteNotEqualTo(String value) {
			addCriterion("producer_website <>", value, "producerWebsite");
			return (Criteria) this;
		}

		public Criteria andProducerWebsiteGreaterThan(String value) {
			addCriterion("producer_website >", value, "producerWebsite");
			return (Criteria) this;
		}

		public Criteria andProducerWebsiteGreaterThanOrEqualTo(String value) {
			addCriterion("producer_website >=", value, "producerWebsite");
			return (Criteria) this;
		}

		public Criteria andProducerWebsiteLessThan(String value) {
			addCriterion("producer_website <", value, "producerWebsite");
			return (Criteria) this;
		}

		public Criteria andProducerWebsiteLessThanOrEqualTo(String value) {
			addCriterion("producer_website <=", value, "producerWebsite");
			return (Criteria) this;
		}

		public Criteria andProducerWebsiteLike(String value) {
			addCriterion("producer_website like", value, "producerWebsite");
			return (Criteria) this;
		}

		public Criteria andProducerWebsiteNotLike(String value) {
			addCriterion("producer_website not like", value, "producerWebsite");
			return (Criteria) this;
		}

		public Criteria andProducerWebsiteIn(List<String> values) {
			addCriterion("producer_website in", values, "producerWebsite");
			return (Criteria) this;
		}

		public Criteria andProducerWebsiteNotIn(List<String> values) {
			addCriterion("producer_website not in", values, "producerWebsite");
			return (Criteria) this;
		}

		public Criteria andProducerWebsiteBetween(String value1, String value2) {
			addCriterion("producer_website between", value1, value2, "producerWebsite");
			return (Criteria) this;
		}

		public Criteria andProducerWebsiteNotBetween(String value1, String value2) {
			addCriterion("producer_website not between", value1, value2, "producerWebsite");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table producer
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table producer
     *
     * @mbggenerated do_not_delete_during_merge Fri May 13 12:51:23 CDT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}