package com.roughindustries.commonwealthcocktails.mybatis.model;

public class Recipe {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column recipe.idrecipe
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private Integer idrecipe;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column recipe.recipe_cocktail
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private Integer recipeCocktail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column recipe.recipe_ingredient
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private Integer recipeIngredient;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column recipe.recipe_doze
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private Float recipeDoze;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column recipe.recipe_cardinal
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private Integer recipeCardinal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column recipe.recipe_ordinal
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private Integer recipeOrdinal;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column recipe.idrecipe
	 * @return  the value of recipe.idrecipe
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public Integer getIdrecipe() {
		return idrecipe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column recipe.idrecipe
	 * @param idrecipe  the value for recipe.idrecipe
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setIdrecipe(Integer idrecipe) {
		this.idrecipe = idrecipe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column recipe.recipe_cocktail
	 * @return  the value of recipe.recipe_cocktail
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public Integer getRecipeCocktail() {
		return recipeCocktail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column recipe.recipe_cocktail
	 * @param recipeCocktail  the value for recipe.recipe_cocktail
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setRecipeCocktail(Integer recipeCocktail) {
		this.recipeCocktail = recipeCocktail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column recipe.recipe_ingredient
	 * @return  the value of recipe.recipe_ingredient
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public Integer getRecipeIngredient() {
		return recipeIngredient;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column recipe.recipe_ingredient
	 * @param recipeIngredient  the value for recipe.recipe_ingredient
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setRecipeIngredient(Integer recipeIngredient) {
		this.recipeIngredient = recipeIngredient;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column recipe.recipe_doze
	 * @return  the value of recipe.recipe_doze
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public Float getRecipeDoze() {
		return recipeDoze;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column recipe.recipe_doze
	 * @param recipeDoze  the value for recipe.recipe_doze
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setRecipeDoze(Float recipeDoze) {
		this.recipeDoze = recipeDoze;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column recipe.recipe_cardinal
	 * @return  the value of recipe.recipe_cardinal
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public Integer getRecipeCardinal() {
		return recipeCardinal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column recipe.recipe_cardinal
	 * @param recipeCardinal  the value for recipe.recipe_cardinal
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setRecipeCardinal(Integer recipeCardinal) {
		this.recipeCardinal = recipeCardinal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column recipe.recipe_ordinal
	 * @return  the value of recipe.recipe_ordinal
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public Integer getRecipeOrdinal() {
		return recipeOrdinal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column recipe.recipe_ordinal
	 * @param recipeOrdinal  the value for recipe.recipe_ordinal
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setRecipeOrdinal(Integer recipeOrdinal) {
		this.recipeOrdinal = recipeOrdinal;
	}
}