package com.roughindustries.commonwealthcocktails.mybatis.model;

public class Sponsorship {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sponsorship.idsponsorship
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private Integer idsponsorship;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sponsorship.sponsorship_component_id
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private Integer sponsorshipComponentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sponsorship.sponsorship_product_id
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private Integer sponsorshipProductId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sponsorship.sponsorship_cocktail_id
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private Integer sponsorshipCocktailId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sponsorship.sponsorship_producer_id
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private Integer sponsorshipProducerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sponsorship.sponsorship_article_id
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private Integer sponsorshipArticleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sponsorship.sponsorship_recipe
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private Integer sponsorshipRecipe;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sponsorship.sponsorship_name
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private String sponsorshipName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sponsorship.sponsorship_site
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private String sponsorshipSite;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sponsorship.sponsorship_image_small
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private String sponsorshipImageSmall;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sponsorship.sponsorship_image_med
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private String sponsorshipImageMed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sponsorship.sponsorship_image_lrg
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	private String sponsorshipImageLrg;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sponsorship.idsponsorship
	 * @return  the value of sponsorship.idsponsorship
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public Integer getIdsponsorship() {
		return idsponsorship;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sponsorship.idsponsorship
	 * @param idsponsorship  the value for sponsorship.idsponsorship
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setIdsponsorship(Integer idsponsorship) {
		this.idsponsorship = idsponsorship;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sponsorship.sponsorship_component_id
	 * @return  the value of sponsorship.sponsorship_component_id
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public Integer getSponsorshipComponentId() {
		return sponsorshipComponentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sponsorship.sponsorship_component_id
	 * @param sponsorshipComponentId  the value for sponsorship.sponsorship_component_id
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setSponsorshipComponentId(Integer sponsorshipComponentId) {
		this.sponsorshipComponentId = sponsorshipComponentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sponsorship.sponsorship_product_id
	 * @return  the value of sponsorship.sponsorship_product_id
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public Integer getSponsorshipProductId() {
		return sponsorshipProductId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sponsorship.sponsorship_product_id
	 * @param sponsorshipProductId  the value for sponsorship.sponsorship_product_id
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setSponsorshipProductId(Integer sponsorshipProductId) {
		this.sponsorshipProductId = sponsorshipProductId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sponsorship.sponsorship_cocktail_id
	 * @return  the value of sponsorship.sponsorship_cocktail_id
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public Integer getSponsorshipCocktailId() {
		return sponsorshipCocktailId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sponsorship.sponsorship_cocktail_id
	 * @param sponsorshipCocktailId  the value for sponsorship.sponsorship_cocktail_id
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setSponsorshipCocktailId(Integer sponsorshipCocktailId) {
		this.sponsorshipCocktailId = sponsorshipCocktailId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sponsorship.sponsorship_producer_id
	 * @return  the value of sponsorship.sponsorship_producer_id
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public Integer getSponsorshipProducerId() {
		return sponsorshipProducerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sponsorship.sponsorship_producer_id
	 * @param sponsorshipProducerId  the value for sponsorship.sponsorship_producer_id
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setSponsorshipProducerId(Integer sponsorshipProducerId) {
		this.sponsorshipProducerId = sponsorshipProducerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sponsorship.sponsorship_article_id
	 * @return  the value of sponsorship.sponsorship_article_id
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public Integer getSponsorshipArticleId() {
		return sponsorshipArticleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sponsorship.sponsorship_article_id
	 * @param sponsorshipArticleId  the value for sponsorship.sponsorship_article_id
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setSponsorshipArticleId(Integer sponsorshipArticleId) {
		this.sponsorshipArticleId = sponsorshipArticleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sponsorship.sponsorship_recipe
	 * @return  the value of sponsorship.sponsorship_recipe
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public Integer getSponsorshipRecipe() {
		return sponsorshipRecipe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sponsorship.sponsorship_recipe
	 * @param sponsorshipRecipe  the value for sponsorship.sponsorship_recipe
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setSponsorshipRecipe(Integer sponsorshipRecipe) {
		this.sponsorshipRecipe = sponsorshipRecipe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sponsorship.sponsorship_name
	 * @return  the value of sponsorship.sponsorship_name
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public String getSponsorshipName() {
		return sponsorshipName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sponsorship.sponsorship_name
	 * @param sponsorshipName  the value for sponsorship.sponsorship_name
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setSponsorshipName(String sponsorshipName) {
		this.sponsorshipName = sponsorshipName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sponsorship.sponsorship_site
	 * @return  the value of sponsorship.sponsorship_site
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public String getSponsorshipSite() {
		return sponsorshipSite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sponsorship.sponsorship_site
	 * @param sponsorshipSite  the value for sponsorship.sponsorship_site
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setSponsorshipSite(String sponsorshipSite) {
		this.sponsorshipSite = sponsorshipSite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sponsorship.sponsorship_image_small
	 * @return  the value of sponsorship.sponsorship_image_small
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public String getSponsorshipImageSmall() {
		return sponsorshipImageSmall;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sponsorship.sponsorship_image_small
	 * @param sponsorshipImageSmall  the value for sponsorship.sponsorship_image_small
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setSponsorshipImageSmall(String sponsorshipImageSmall) {
		this.sponsorshipImageSmall = sponsorshipImageSmall;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sponsorship.sponsorship_image_med
	 * @return  the value of sponsorship.sponsorship_image_med
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public String getSponsorshipImageMed() {
		return sponsorshipImageMed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sponsorship.sponsorship_image_med
	 * @param sponsorshipImageMed  the value for sponsorship.sponsorship_image_med
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setSponsorshipImageMed(String sponsorshipImageMed) {
		this.sponsorshipImageMed = sponsorshipImageMed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sponsorship.sponsorship_image_lrg
	 * @return  the value of sponsorship.sponsorship_image_lrg
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public String getSponsorshipImageLrg() {
		return sponsorshipImageLrg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sponsorship.sponsorship_image_lrg
	 * @param sponsorshipImageLrg  the value for sponsorship.sponsorship_image_lrg
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setSponsorshipImageLrg(String sponsorshipImageLrg) {
		this.sponsorshipImageLrg = sponsorshipImageLrg;
	}
}