package com.roughindustries.commonwealthcocktails.mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class SponsorshipExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sponsorship
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sponsorship
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sponsorship
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sponsorship
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public SponsorshipExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sponsorship
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sponsorship
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sponsorship
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sponsorship
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sponsorship
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sponsorship
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sponsorship
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sponsorship
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sponsorship
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sponsorship
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sponsorship
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdsponsorshipIsNull() {
			addCriterion("idsponsorship is null");
			return (Criteria) this;
		}

		public Criteria andIdsponsorshipIsNotNull() {
			addCriterion("idsponsorship is not null");
			return (Criteria) this;
		}

		public Criteria andIdsponsorshipEqualTo(Integer value) {
			addCriterion("idsponsorship =", value, "idsponsorship");
			return (Criteria) this;
		}

		public Criteria andIdsponsorshipNotEqualTo(Integer value) {
			addCriterion("idsponsorship <>", value, "idsponsorship");
			return (Criteria) this;
		}

		public Criteria andIdsponsorshipGreaterThan(Integer value) {
			addCriterion("idsponsorship >", value, "idsponsorship");
			return (Criteria) this;
		}

		public Criteria andIdsponsorshipGreaterThanOrEqualTo(Integer value) {
			addCriterion("idsponsorship >=", value, "idsponsorship");
			return (Criteria) this;
		}

		public Criteria andIdsponsorshipLessThan(Integer value) {
			addCriterion("idsponsorship <", value, "idsponsorship");
			return (Criteria) this;
		}

		public Criteria andIdsponsorshipLessThanOrEqualTo(Integer value) {
			addCriterion("idsponsorship <=", value, "idsponsorship");
			return (Criteria) this;
		}

		public Criteria andIdsponsorshipIn(List<Integer> values) {
			addCriterion("idsponsorship in", values, "idsponsorship");
			return (Criteria) this;
		}

		public Criteria andIdsponsorshipNotIn(List<Integer> values) {
			addCriterion("idsponsorship not in", values, "idsponsorship");
			return (Criteria) this;
		}

		public Criteria andIdsponsorshipBetween(Integer value1, Integer value2) {
			addCriterion("idsponsorship between", value1, value2, "idsponsorship");
			return (Criteria) this;
		}

		public Criteria andIdsponsorshipNotBetween(Integer value1, Integer value2) {
			addCriterion("idsponsorship not between", value1, value2, "idsponsorship");
			return (Criteria) this;
		}

		public Criteria andSponsorshipComponentIdIsNull() {
			addCriterion("sponsorship_component_id is null");
			return (Criteria) this;
		}

		public Criteria andSponsorshipComponentIdIsNotNull() {
			addCriterion("sponsorship_component_id is not null");
			return (Criteria) this;
		}

		public Criteria andSponsorshipComponentIdEqualTo(Integer value) {
			addCriterion("sponsorship_component_id =", value, "sponsorshipComponentId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipComponentIdNotEqualTo(Integer value) {
			addCriterion("sponsorship_component_id <>", value, "sponsorshipComponentId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipComponentIdGreaterThan(Integer value) {
			addCriterion("sponsorship_component_id >", value, "sponsorshipComponentId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipComponentIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("sponsorship_component_id >=", value, "sponsorshipComponentId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipComponentIdLessThan(Integer value) {
			addCriterion("sponsorship_component_id <", value, "sponsorshipComponentId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipComponentIdLessThanOrEqualTo(Integer value) {
			addCriterion("sponsorship_component_id <=", value, "sponsorshipComponentId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipComponentIdIn(List<Integer> values) {
			addCriterion("sponsorship_component_id in", values, "sponsorshipComponentId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipComponentIdNotIn(List<Integer> values) {
			addCriterion("sponsorship_component_id not in", values, "sponsorshipComponentId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipComponentIdBetween(Integer value1, Integer value2) {
			addCriterion("sponsorship_component_id between", value1, value2, "sponsorshipComponentId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipComponentIdNotBetween(Integer value1, Integer value2) {
			addCriterion("sponsorship_component_id not between", value1, value2, "sponsorshipComponentId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipProductIdIsNull() {
			addCriterion("sponsorship_product_id is null");
			return (Criteria) this;
		}

		public Criteria andSponsorshipProductIdIsNotNull() {
			addCriterion("sponsorship_product_id is not null");
			return (Criteria) this;
		}

		public Criteria andSponsorshipProductIdEqualTo(Integer value) {
			addCriterion("sponsorship_product_id =", value, "sponsorshipProductId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipProductIdNotEqualTo(Integer value) {
			addCriterion("sponsorship_product_id <>", value, "sponsorshipProductId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipProductIdGreaterThan(Integer value) {
			addCriterion("sponsorship_product_id >", value, "sponsorshipProductId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipProductIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("sponsorship_product_id >=", value, "sponsorshipProductId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipProductIdLessThan(Integer value) {
			addCriterion("sponsorship_product_id <", value, "sponsorshipProductId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipProductIdLessThanOrEqualTo(Integer value) {
			addCriterion("sponsorship_product_id <=", value, "sponsorshipProductId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipProductIdIn(List<Integer> values) {
			addCriterion("sponsorship_product_id in", values, "sponsorshipProductId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipProductIdNotIn(List<Integer> values) {
			addCriterion("sponsorship_product_id not in", values, "sponsorshipProductId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipProductIdBetween(Integer value1, Integer value2) {
			addCriterion("sponsorship_product_id between", value1, value2, "sponsorshipProductId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipProductIdNotBetween(Integer value1, Integer value2) {
			addCriterion("sponsorship_product_id not between", value1, value2, "sponsorshipProductId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipCocktailIdIsNull() {
			addCriterion("sponsorship_cocktail_id is null");
			return (Criteria) this;
		}

		public Criteria andSponsorshipCocktailIdIsNotNull() {
			addCriterion("sponsorship_cocktail_id is not null");
			return (Criteria) this;
		}

		public Criteria andSponsorshipCocktailIdEqualTo(Integer value) {
			addCriterion("sponsorship_cocktail_id =", value, "sponsorshipCocktailId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipCocktailIdNotEqualTo(Integer value) {
			addCriterion("sponsorship_cocktail_id <>", value, "sponsorshipCocktailId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipCocktailIdGreaterThan(Integer value) {
			addCriterion("sponsorship_cocktail_id >", value, "sponsorshipCocktailId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipCocktailIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("sponsorship_cocktail_id >=", value, "sponsorshipCocktailId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipCocktailIdLessThan(Integer value) {
			addCriterion("sponsorship_cocktail_id <", value, "sponsorshipCocktailId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipCocktailIdLessThanOrEqualTo(Integer value) {
			addCriterion("sponsorship_cocktail_id <=", value, "sponsorshipCocktailId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipCocktailIdIn(List<Integer> values) {
			addCriterion("sponsorship_cocktail_id in", values, "sponsorshipCocktailId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipCocktailIdNotIn(List<Integer> values) {
			addCriterion("sponsorship_cocktail_id not in", values, "sponsorshipCocktailId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipCocktailIdBetween(Integer value1, Integer value2) {
			addCriterion("sponsorship_cocktail_id between", value1, value2, "sponsorshipCocktailId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipCocktailIdNotBetween(Integer value1, Integer value2) {
			addCriterion("sponsorship_cocktail_id not between", value1, value2, "sponsorshipCocktailId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipProducerIdIsNull() {
			addCriterion("sponsorship_producer_id is null");
			return (Criteria) this;
		}

		public Criteria andSponsorshipProducerIdIsNotNull() {
			addCriterion("sponsorship_producer_id is not null");
			return (Criteria) this;
		}

		public Criteria andSponsorshipProducerIdEqualTo(Integer value) {
			addCriterion("sponsorship_producer_id =", value, "sponsorshipProducerId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipProducerIdNotEqualTo(Integer value) {
			addCriterion("sponsorship_producer_id <>", value, "sponsorshipProducerId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipProducerIdGreaterThan(Integer value) {
			addCriterion("sponsorship_producer_id >", value, "sponsorshipProducerId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipProducerIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("sponsorship_producer_id >=", value, "sponsorshipProducerId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipProducerIdLessThan(Integer value) {
			addCriterion("sponsorship_producer_id <", value, "sponsorshipProducerId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipProducerIdLessThanOrEqualTo(Integer value) {
			addCriterion("sponsorship_producer_id <=", value, "sponsorshipProducerId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipProducerIdIn(List<Integer> values) {
			addCriterion("sponsorship_producer_id in", values, "sponsorshipProducerId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipProducerIdNotIn(List<Integer> values) {
			addCriterion("sponsorship_producer_id not in", values, "sponsorshipProducerId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipProducerIdBetween(Integer value1, Integer value2) {
			addCriterion("sponsorship_producer_id between", value1, value2, "sponsorshipProducerId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipProducerIdNotBetween(Integer value1, Integer value2) {
			addCriterion("sponsorship_producer_id not between", value1, value2, "sponsorshipProducerId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipArticleIdIsNull() {
			addCriterion("sponsorship_article_id is null");
			return (Criteria) this;
		}

		public Criteria andSponsorshipArticleIdIsNotNull() {
			addCriterion("sponsorship_article_id is not null");
			return (Criteria) this;
		}

		public Criteria andSponsorshipArticleIdEqualTo(Integer value) {
			addCriterion("sponsorship_article_id =", value, "sponsorshipArticleId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipArticleIdNotEqualTo(Integer value) {
			addCriterion("sponsorship_article_id <>", value, "sponsorshipArticleId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipArticleIdGreaterThan(Integer value) {
			addCriterion("sponsorship_article_id >", value, "sponsorshipArticleId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipArticleIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("sponsorship_article_id >=", value, "sponsorshipArticleId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipArticleIdLessThan(Integer value) {
			addCriterion("sponsorship_article_id <", value, "sponsorshipArticleId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipArticleIdLessThanOrEqualTo(Integer value) {
			addCriterion("sponsorship_article_id <=", value, "sponsorshipArticleId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipArticleIdIn(List<Integer> values) {
			addCriterion("sponsorship_article_id in", values, "sponsorshipArticleId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipArticleIdNotIn(List<Integer> values) {
			addCriterion("sponsorship_article_id not in", values, "sponsorshipArticleId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipArticleIdBetween(Integer value1, Integer value2) {
			addCriterion("sponsorship_article_id between", value1, value2, "sponsorshipArticleId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipArticleIdNotBetween(Integer value1, Integer value2) {
			addCriterion("sponsorship_article_id not between", value1, value2, "sponsorshipArticleId");
			return (Criteria) this;
		}

		public Criteria andSponsorshipRecipeIsNull() {
			addCriterion("sponsorship_recipe is null");
			return (Criteria) this;
		}

		public Criteria andSponsorshipRecipeIsNotNull() {
			addCriterion("sponsorship_recipe is not null");
			return (Criteria) this;
		}

		public Criteria andSponsorshipRecipeEqualTo(Integer value) {
			addCriterion("sponsorship_recipe =", value, "sponsorshipRecipe");
			return (Criteria) this;
		}

		public Criteria andSponsorshipRecipeNotEqualTo(Integer value) {
			addCriterion("sponsorship_recipe <>", value, "sponsorshipRecipe");
			return (Criteria) this;
		}

		public Criteria andSponsorshipRecipeGreaterThan(Integer value) {
			addCriterion("sponsorship_recipe >", value, "sponsorshipRecipe");
			return (Criteria) this;
		}

		public Criteria andSponsorshipRecipeGreaterThanOrEqualTo(Integer value) {
			addCriterion("sponsorship_recipe >=", value, "sponsorshipRecipe");
			return (Criteria) this;
		}

		public Criteria andSponsorshipRecipeLessThan(Integer value) {
			addCriterion("sponsorship_recipe <", value, "sponsorshipRecipe");
			return (Criteria) this;
		}

		public Criteria andSponsorshipRecipeLessThanOrEqualTo(Integer value) {
			addCriterion("sponsorship_recipe <=", value, "sponsorshipRecipe");
			return (Criteria) this;
		}

		public Criteria andSponsorshipRecipeIn(List<Integer> values) {
			addCriterion("sponsorship_recipe in", values, "sponsorshipRecipe");
			return (Criteria) this;
		}

		public Criteria andSponsorshipRecipeNotIn(List<Integer> values) {
			addCriterion("sponsorship_recipe not in", values, "sponsorshipRecipe");
			return (Criteria) this;
		}

		public Criteria andSponsorshipRecipeBetween(Integer value1, Integer value2) {
			addCriterion("sponsorship_recipe between", value1, value2, "sponsorshipRecipe");
			return (Criteria) this;
		}

		public Criteria andSponsorshipRecipeNotBetween(Integer value1, Integer value2) {
			addCriterion("sponsorship_recipe not between", value1, value2, "sponsorshipRecipe");
			return (Criteria) this;
		}

		public Criteria andSponsorshipNameIsNull() {
			addCriterion("sponsorship_name is null");
			return (Criteria) this;
		}

		public Criteria andSponsorshipNameIsNotNull() {
			addCriterion("sponsorship_name is not null");
			return (Criteria) this;
		}

		public Criteria andSponsorshipNameEqualTo(String value) {
			addCriterion("sponsorship_name =", value, "sponsorshipName");
			return (Criteria) this;
		}

		public Criteria andSponsorshipNameNotEqualTo(String value) {
			addCriterion("sponsorship_name <>", value, "sponsorshipName");
			return (Criteria) this;
		}

		public Criteria andSponsorshipNameGreaterThan(String value) {
			addCriterion("sponsorship_name >", value, "sponsorshipName");
			return (Criteria) this;
		}

		public Criteria andSponsorshipNameGreaterThanOrEqualTo(String value) {
			addCriterion("sponsorship_name >=", value, "sponsorshipName");
			return (Criteria) this;
		}

		public Criteria andSponsorshipNameLessThan(String value) {
			addCriterion("sponsorship_name <", value, "sponsorshipName");
			return (Criteria) this;
		}

		public Criteria andSponsorshipNameLessThanOrEqualTo(String value) {
			addCriterion("sponsorship_name <=", value, "sponsorshipName");
			return (Criteria) this;
		}

		public Criteria andSponsorshipNameLike(String value) {
			addCriterion("sponsorship_name like", value, "sponsorshipName");
			return (Criteria) this;
		}

		public Criteria andSponsorshipNameNotLike(String value) {
			addCriterion("sponsorship_name not like", value, "sponsorshipName");
			return (Criteria) this;
		}

		public Criteria andSponsorshipNameIn(List<String> values) {
			addCriterion("sponsorship_name in", values, "sponsorshipName");
			return (Criteria) this;
		}

		public Criteria andSponsorshipNameNotIn(List<String> values) {
			addCriterion("sponsorship_name not in", values, "sponsorshipName");
			return (Criteria) this;
		}

		public Criteria andSponsorshipNameBetween(String value1, String value2) {
			addCriterion("sponsorship_name between", value1, value2, "sponsorshipName");
			return (Criteria) this;
		}

		public Criteria andSponsorshipNameNotBetween(String value1, String value2) {
			addCriterion("sponsorship_name not between", value1, value2, "sponsorshipName");
			return (Criteria) this;
		}

		public Criteria andSponsorshipSiteIsNull() {
			addCriterion("sponsorship_site is null");
			return (Criteria) this;
		}

		public Criteria andSponsorshipSiteIsNotNull() {
			addCriterion("sponsorship_site is not null");
			return (Criteria) this;
		}

		public Criteria andSponsorshipSiteEqualTo(String value) {
			addCriterion("sponsorship_site =", value, "sponsorshipSite");
			return (Criteria) this;
		}

		public Criteria andSponsorshipSiteNotEqualTo(String value) {
			addCriterion("sponsorship_site <>", value, "sponsorshipSite");
			return (Criteria) this;
		}

		public Criteria andSponsorshipSiteGreaterThan(String value) {
			addCriterion("sponsorship_site >", value, "sponsorshipSite");
			return (Criteria) this;
		}

		public Criteria andSponsorshipSiteGreaterThanOrEqualTo(String value) {
			addCriterion("sponsorship_site >=", value, "sponsorshipSite");
			return (Criteria) this;
		}

		public Criteria andSponsorshipSiteLessThan(String value) {
			addCriterion("sponsorship_site <", value, "sponsorshipSite");
			return (Criteria) this;
		}

		public Criteria andSponsorshipSiteLessThanOrEqualTo(String value) {
			addCriterion("sponsorship_site <=", value, "sponsorshipSite");
			return (Criteria) this;
		}

		public Criteria andSponsorshipSiteLike(String value) {
			addCriterion("sponsorship_site like", value, "sponsorshipSite");
			return (Criteria) this;
		}

		public Criteria andSponsorshipSiteNotLike(String value) {
			addCriterion("sponsorship_site not like", value, "sponsorshipSite");
			return (Criteria) this;
		}

		public Criteria andSponsorshipSiteIn(List<String> values) {
			addCriterion("sponsorship_site in", values, "sponsorshipSite");
			return (Criteria) this;
		}

		public Criteria andSponsorshipSiteNotIn(List<String> values) {
			addCriterion("sponsorship_site not in", values, "sponsorshipSite");
			return (Criteria) this;
		}

		public Criteria andSponsorshipSiteBetween(String value1, String value2) {
			addCriterion("sponsorship_site between", value1, value2, "sponsorshipSite");
			return (Criteria) this;
		}

		public Criteria andSponsorshipSiteNotBetween(String value1, String value2) {
			addCriterion("sponsorship_site not between", value1, value2, "sponsorshipSite");
			return (Criteria) this;
		}

		public Criteria andSponsorshipImageSmallIsNull() {
			addCriterion("sponsorship_image_small is null");
			return (Criteria) this;
		}

		public Criteria andSponsorshipImageSmallIsNotNull() {
			addCriterion("sponsorship_image_small is not null");
			return (Criteria) this;
		}

		public Criteria andSponsorshipImageSmallEqualTo(String value) {
			addCriterion("sponsorship_image_small =", value, "sponsorshipImageSmall");
			return (Criteria) this;
		}

		public Criteria andSponsorshipImageSmallNotEqualTo(String value) {
			addCriterion("sponsorship_image_small <>", value, "sponsorshipImageSmall");
			return (Criteria) this;
		}

		public Criteria andSponsorshipImageSmallGreaterThan(String value) {
			addCriterion("sponsorship_image_small >", value, "sponsorshipImageSmall");
			return (Criteria) this;
		}

		public Criteria andSponsorshipImageSmallGreaterThanOrEqualTo(String value) {
			addCriterion("sponsorship_image_small >=", value, "sponsorshipImageSmall");
			return (Criteria) this;
		}

		public Criteria andSponsorshipImageSmallLessThan(String value) {
			addCriterion("sponsorship_image_small <", value, "sponsorshipImageSmall");
			return (Criteria) this;
		}

		public Criteria andSponsorshipImageSmallLessThanOrEqualTo(String value) {
			addCriterion("sponsorship_image_small <=", value, "sponsorshipImageSmall");
			return (Criteria) this;
		}

		public Criteria andSponsorshipImageSmallLike(String value) {
			addCriterion("sponsorship_image_small like", value, "sponsorshipImageSmall");
			return (Criteria) this;
		}

		public Criteria andSponsorshipImageSmallNotLike(String value) {
			addCriterion("sponsorship_image_small not like", value, "sponsorshipImageSmall");
			return (Criteria) this;
		}

		public Criteria andSponsorshipImageSmallIn(List<String> values) {
			addCriterion("sponsorship_image_small in", values, "sponsorshipImageSmall");
			return (Criteria) this;
		}

		public Criteria andSponsorshipImageSmallNotIn(List<String> values) {
			addCriterion("sponsorship_image_small not in", values, "sponsorshipImageSmall");
			return (Criteria) this;
		}

		public Criteria andSponsorshipImageSmallBetween(String value1, String value2) {
			addCriterion("sponsorship_image_small between", value1, value2, "sponsorshipImageSmall");
			return (Criteria) this;
		}

		public Criteria andSponsorshipImageSmallNotBetween(String value1, String value2) {
			addCriterion("sponsorship_image_small not between", value1, value2, "sponsorshipImageSmall");
			return (Criteria) this;
		}

		public Criteria andSponsorshipImageMedIsNull() {
			addCriterion("sponsorship_image_med is null");
			return (Criteria) this;
		}

		public Criteria andSponsorshipImageMedIsNotNull() {
			addCriterion("sponsorship_image_med is not null");
			return (Criteria) this;
		}

		public Criteria andSponsorshipImageMedEqualTo(String value) {
			addCriterion("sponsorship_image_med =", value, "sponsorshipImageMed");
			return (Criteria) this;
		}

		public Criteria andSponsorshipImageMedNotEqualTo(String value) {
			addCriterion("sponsorship_image_med <>", value, "sponsorshipImageMed");
			return (Criteria) this;
		}

		public Criteria andSponsorshipImageMedGreaterThan(String value) {
			addCriterion("sponsorship_image_med >", value, "sponsorshipImageMed");
			return (Criteria) this;
		}

		public Criteria andSponsorshipImageMedGreaterThanOrEqualTo(String value) {
			addCriterion("sponsorship_image_med >=", value, "sponsorshipImageMed");
			return (Criteria) this;
		}

		public Criteria andSponsorshipImageMedLessThan(String value) {
			addCriterion("sponsorship_image_med <", value, "sponsorshipImageMed");
			return (Criteria) this;
		}

		public Criteria andSponsorshipImageMedLessThanOrEqualTo(String value) {
			addCriterion("sponsorship_image_med <=", value, "sponsorshipImageMed");
			return (Criteria) this;
		}

		public Criteria andSponsorshipImageMedLike(String value) {
			addCriterion("sponsorship_image_med like", value, "sponsorshipImageMed");
			return (Criteria) this;
		}

		public Criteria andSponsorshipImageMedNotLike(String value) {
			addCriterion("sponsorship_image_med not like", value, "sponsorshipImageMed");
			return (Criteria) this;
		}

		public Criteria andSponsorshipImageMedIn(List<String> values) {
			addCriterion("sponsorship_image_med in", values, "sponsorshipImageMed");
			return (Criteria) this;
		}

		public Criteria andSponsorshipImageMedNotIn(List<String> values) {
			addCriterion("sponsorship_image_med not in", values, "sponsorshipImageMed");
			return (Criteria) this;
		}

		public Criteria andSponsorshipImageMedBetween(String value1, String value2) {
			addCriterion("sponsorship_image_med between", value1, value2, "sponsorshipImageMed");
			return (Criteria) this;
		}

		public Criteria andSponsorshipImageMedNotBetween(String value1, String value2) {
			addCriterion("sponsorship_image_med not between", value1, value2, "sponsorshipImageMed");
			return (Criteria) this;
		}

		public Criteria andSponsorshipImageLrgIsNull() {
			addCriterion("sponsorship_image_lrg is null");
			return (Criteria) this;
		}

		public Criteria andSponsorshipImageLrgIsNotNull() {
			addCriterion("sponsorship_image_lrg is not null");
			return (Criteria) this;
		}

		public Criteria andSponsorshipImageLrgEqualTo(String value) {
			addCriterion("sponsorship_image_lrg =", value, "sponsorshipImageLrg");
			return (Criteria) this;
		}

		public Criteria andSponsorshipImageLrgNotEqualTo(String value) {
			addCriterion("sponsorship_image_lrg <>", value, "sponsorshipImageLrg");
			return (Criteria) this;
		}

		public Criteria andSponsorshipImageLrgGreaterThan(String value) {
			addCriterion("sponsorship_image_lrg >", value, "sponsorshipImageLrg");
			return (Criteria) this;
		}

		public Criteria andSponsorshipImageLrgGreaterThanOrEqualTo(String value) {
			addCriterion("sponsorship_image_lrg >=", value, "sponsorshipImageLrg");
			return (Criteria) this;
		}

		public Criteria andSponsorshipImageLrgLessThan(String value) {
			addCriterion("sponsorship_image_lrg <", value, "sponsorshipImageLrg");
			return (Criteria) this;
		}

		public Criteria andSponsorshipImageLrgLessThanOrEqualTo(String value) {
			addCriterion("sponsorship_image_lrg <=", value, "sponsorshipImageLrg");
			return (Criteria) this;
		}

		public Criteria andSponsorshipImageLrgLike(String value) {
			addCriterion("sponsorship_image_lrg like", value, "sponsorshipImageLrg");
			return (Criteria) this;
		}

		public Criteria andSponsorshipImageLrgNotLike(String value) {
			addCriterion("sponsorship_image_lrg not like", value, "sponsorshipImageLrg");
			return (Criteria) this;
		}

		public Criteria andSponsorshipImageLrgIn(List<String> values) {
			addCriterion("sponsorship_image_lrg in", values, "sponsorshipImageLrg");
			return (Criteria) this;
		}

		public Criteria andSponsorshipImageLrgNotIn(List<String> values) {
			addCriterion("sponsorship_image_lrg not in", values, "sponsorshipImageLrg");
			return (Criteria) this;
		}

		public Criteria andSponsorshipImageLrgBetween(String value1, String value2) {
			addCriterion("sponsorship_image_lrg between", value1, value2, "sponsorshipImageLrg");
			return (Criteria) this;
		}

		public Criteria andSponsorshipImageLrgNotBetween(String value1, String value2) {
			addCriterion("sponsorship_image_lrg not between", value1, value2, "sponsorshipImageLrg");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sponsorship
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sponsorship
     *
     * @mbggenerated do_not_delete_during_merge Fri May 13 12:51:23 CDT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}