package com.roughindustries.commonwealthcocktails.mybatis.client;

import com.roughindustries.commonwealthcocktails.mybatis.model.Article;
import com.roughindustries.commonwealthcocktails.mybatis.model.ArticleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int countByExample(ArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int deleteByExample(ArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int deleteByPrimaryKey(Integer idarticle);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int insert(Article record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int insertSelective(Article record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	List<Article> selectByExample(ArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	Article selectByPrimaryKey(Integer idarticle);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int updateByExampleSelective(@Param("record") Article record, @Param("example") ArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int updateByExample(@Param("record") Article record, @Param("example") ArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int updateByPrimaryKeySelective(Article record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int updateByPrimaryKey(Article record);
}