package com.roughindustries.commonwealthcocktails.mybatis.client;

import com.roughindustries.commonwealthcocktails.mybatis.model.Categories;
import com.roughindustries.commonwealthcocktails.mybatis.model.CategoriesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CategoriesMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table categories
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int countByExample(CategoriesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table categories
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int deleteByExample(CategoriesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table categories
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int deleteByPrimaryKey(Integer idcategory);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table categories
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int insert(Categories record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table categories
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int insertSelective(Categories record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table categories
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	List<Categories> selectByExample(CategoriesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table categories
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	Categories selectByPrimaryKey(Integer idcategory);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table categories
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int updateByExampleSelective(@Param("record") Categories record, @Param("example") CategoriesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table categories
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int updateByExample(@Param("record") Categories record, @Param("example") CategoriesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table categories
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int updateByPrimaryKeySelective(Categories record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table categories
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int updateByPrimaryKey(Categories record);
}