package com.roughindustries.commonwealthcocktails.mybatis.client;

import com.roughindustries.commonwealthcocktails.mybatis.model.Cocktail;
import com.roughindustries.commonwealthcocktails.mybatis.model.CocktailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CocktailMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cocktail
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int countByExample(CocktailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cocktail
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int deleteByExample(CocktailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cocktail
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int deleteByPrimaryKey(Integer idcocktail);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cocktail
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int insert(Cocktail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cocktail
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int insertSelective(Cocktail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cocktail
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	List<Cocktail> selectByExample(CocktailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cocktail
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	Cocktail selectByPrimaryKey(Integer idcocktail);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cocktail
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int updateByExampleSelective(@Param("record") Cocktail record, @Param("example") CocktailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cocktail
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int updateByExample(@Param("record") Cocktail record, @Param("example") CocktailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cocktail
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int updateByPrimaryKeySelective(Cocktail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cocktail
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int updateByPrimaryKey(Cocktail record);
}