package com.roughindustries.commonwealthcocktails.mybatis.client;

import com.roughindustries.commonwealthcocktails.mybatis.model.Component2product;
import com.roughindustries.commonwealthcocktails.mybatis.model.Component2productExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Component2productMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table component2product
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int countByExample(Component2productExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table component2product
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int deleteByExample(Component2productExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table component2product
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int deleteByPrimaryKey(Integer idcomponent2product);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table component2product
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int insert(Component2product record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table component2product
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int insertSelective(Component2product record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table component2product
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	List<Component2product> selectByExample(Component2productExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table component2product
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	Component2product selectByPrimaryKey(Integer idcomponent2product);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table component2product
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int updateByExampleSelective(@Param("record") Component2product record,
			@Param("example") Component2productExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table component2product
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int updateByExample(@Param("record") Component2product record, @Param("example") Component2productExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table component2product
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int updateByPrimaryKeySelective(Component2product record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table component2product
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int updateByPrimaryKey(Component2product record);
}