package com.roughindustries.commonwealthcocktails.mybatis.client;

import com.roughindustries.commonwealthcocktails.mybatis.model.Component;
import com.roughindustries.commonwealthcocktails.mybatis.model.ComponentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComponentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table component
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int countByExample(ComponentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table component
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int deleteByExample(ComponentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table component
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int deleteByPrimaryKey(Integer idcomponent);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table component
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int insert(Component record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table component
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int insertSelective(Component record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table component
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	List<Component> selectByExample(ComponentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table component
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	Component selectByPrimaryKey(Integer idcomponent);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table component
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int updateByExampleSelective(@Param("record") Component record, @Param("example") ComponentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table component
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int updateByExample(@Param("record") Component record, @Param("example") ComponentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table component
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int updateByPrimaryKeySelective(Component record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table component
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int updateByPrimaryKey(Component record);
}