package com.roughindustries.commonwealthcocktails.mybatis.client;

import com.roughindustries.commonwealthcocktails.mybatis.model.Component2cocktail;
import com.roughindustries.commonwealthcocktails.mybatis.model.Component2cocktailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Component2cocktailMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table component2cocktail
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int countByExample(Component2cocktailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table component2cocktail
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int deleteByExample(Component2cocktailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table component2cocktail
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int insert(Component2cocktail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table component2cocktail
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int insertSelective(Component2cocktail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table component2cocktail
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	List<Component2cocktail> selectByExample(Component2cocktailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table component2cocktail
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int updateByExampleSelective(@Param("record") Component2cocktail record,
			@Param("example") Component2cocktailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table component2cocktail
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int updateByExample(@Param("record") Component2cocktail record,
			@Param("example") Component2cocktailExample example);
}