package com.roughindustries.commonwealthcocktails.mybatis.client;

import com.roughindustries.commonwealthcocktails.mybatis.model.Product;
import com.roughindustries.commonwealthcocktails.mybatis.model.ProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int countByExample(ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int deleteByExample(ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int deleteByPrimaryKey(Integer idproducts);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int insert(Product record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int insertSelective(Product record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	List<Product> selectByExample(ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	Product selectByPrimaryKey(Integer idproducts);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int updateByExampleSelective(@Param("record") Product record, @Param("example") ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int updateByExample(@Param("record") Product record, @Param("example") ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int updateByPrimaryKeySelective(Product record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int updateByPrimaryKey(Product record);
}