package com.roughindustries.commonwealthcocktails.mybatis.client;

import com.roughindustries.commonwealthcocktails.mybatis.model.Producer;
import com.roughindustries.commonwealthcocktails.mybatis.model.ProducerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProducerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producer
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int countByExample(ProducerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producer
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int deleteByExample(ProducerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producer
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int deleteByPrimaryKey(Integer idproducer);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producer
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int insert(Producer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producer
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int insertSelective(Producer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producer
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	List<Producer> selectByExample(ProducerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producer
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	Producer selectByPrimaryKey(Integer idproducer);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producer
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int updateByExampleSelective(@Param("record") Producer record, @Param("example") ProducerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producer
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int updateByExample(@Param("record") Producer record, @Param("example") ProducerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producer
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int updateByPrimaryKeySelective(Producer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producer
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int updateByPrimaryKey(Producer record);
}