package com.roughindustries.commonwealthcocktails.mybatis.client;

import com.roughindustries.commonwealthcocktails.mybatis.model.Recipe;
import com.roughindustries.commonwealthcocktails.mybatis.model.RecipeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RecipeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recipe
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int countByExample(RecipeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recipe
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int deleteByExample(RecipeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recipe
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int deleteByPrimaryKey(Integer idrecipe);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recipe
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int insert(Recipe record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recipe
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int insertSelective(Recipe record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recipe
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	List<Recipe> selectByExample(RecipeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recipe
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	Recipe selectByPrimaryKey(Integer idrecipe);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recipe
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int updateByExampleSelective(@Param("record") Recipe record, @Param("example") RecipeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recipe
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int updateByExample(@Param("record") Recipe record, @Param("example") RecipeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recipe
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int updateByPrimaryKeySelective(Recipe record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recipe
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int updateByPrimaryKey(Recipe record);
}