package com.roughindustries.commonwealthcocktails.mybatis.client;

import com.roughindustries.commonwealthcocktails.mybatis.model.Sponsorship;
import com.roughindustries.commonwealthcocktails.mybatis.model.SponsorshipExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SponsorshipMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sponsorship
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int countByExample(SponsorshipExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sponsorship
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int deleteByExample(SponsorshipExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sponsorship
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int deleteByPrimaryKey(Integer idsponsorship);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sponsorship
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int insert(Sponsorship record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sponsorship
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int insertSelective(Sponsorship record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sponsorship
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	List<Sponsorship> selectByExample(SponsorshipExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sponsorship
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	Sponsorship selectByPrimaryKey(Integer idsponsorship);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sponsorship
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int updateByExampleSelective(@Param("record") Sponsorship record, @Param("example") SponsorshipExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sponsorship
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int updateByExample(@Param("record") Sponsorship record, @Param("example") SponsorshipExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sponsorship
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int updateByPrimaryKeySelective(Sponsorship record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sponsorship
	 * @mbggenerated  Fri May 13 13:15:11 CDT 2016
	 */
	int updateByPrimaryKey(Sponsorship record);
}